-- Seed Grumm — base saine de 50 faits
-- Structure éditoriale : title / content / hook / long_content
-- À exécuter après remise à zéro des faits, catégories et interactions.
-- Idempotent : catégories upsert, faits upsert par slug.

BEGIN;

INSERT INTO public.categories (slug, name, accent_color, tone)
VALUES
  ('histoire', 'Histoire', '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),
  ('cinema-culture-pop', 'Cinéma & culture pop', '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),
  ('grandes-figures', 'Grandes figures', '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),
  ('arts-litterature', 'Arts & littérature', '#06b6d4', 'from-[#071a20] via-[#164e63] to-[#67e8f9]'),
  ('science', 'Science', '#22c55e', 'from-[#061a12] via-[#14532d] to-[#86efac]'),
  ('inventions-technologie', 'Inventions & technologie', '#3b82f6', 'from-[#071426] via-[#1d4ed8] to-[#93c5fd]'),
  ('quotidien-societe', 'Quotidien & société', '#f59e0b', 'from-[#1c1608] via-[#92400e] to-[#fbbf24]'),
  ('mots-origines', 'Mots & origines', '#14b8a6', 'from-[#06221f] via-[#0f766e] to-[#5eead4]'),
  ('geographie', 'Géographie', '#84cc16', 'from-[#101a08] via-[#3f6212] to-[#bef264]'),
  ('musique', 'Musique', '#ef4444', 'from-[#220b0b] via-[#991b1b] to-[#fca5a5]')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  accent_color = EXCLUDED.accent_color,
  tone = EXCLUDED.tone,
  updated_at = now();

WITH fact_seed (
  category_slug,
  slug,
  title,
  hook,
  content,
  long_content,
  source,
  source_url,
  display_order,
  accent_color,
  tone
) AS (
VALUES
  ('histoire-essentielle', 'la-premiere-guerre-mondiale-a-commence-en-1914',
  'La Première Guerre mondiale a commencé en 1914.',
  'Un conflit pensé court a bouleversé tout le XXe siècle.',
  'Après l’assassinat de l’archiduc François-Ferdinand, les alliances entre pays européens entraînent rapidement une guerre immense. Beaucoup pensent alors que le conflit sera court, mais il durera plus de quatre ans.',
  'La Première Guerre mondiale commence en 1914 dans un climat de tensions entre grandes puissances européennes. L’assassinat de l’archiduc François-Ferdinand à Sarajevo déclenche une réaction en chaîne diplomatique et militaire. Le conflit s’étend ensuite bien au-delà de l’Europe. Il bouleverse les frontières, affaiblit plusieurs empires et marque durablement la mémoire collective. Comprendre 1914 aide à mieux comprendre une grande partie du XXe siècle.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/event/World-War-I', 1, '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),

  ('histoire-essentielle', 'la-revolution-francaise-a-commence-en-1789',
  'La Révolution française a commencé en 1789.',
  '1789 marque le début d’un basculement politique français.',
  'Cette date ouvre une période de bouleversements majeurs en France. La prise de la Bastille, le 14 juillet 1789, devient rapidement le symbole d’un peuple qui conteste l’autorité royale.',
  'En 1789, la France traverse une crise financière, sociale et politique profonde. Les inégalités entre les ordres, la dette de l’État et les tensions populaires fragilisent l’Ancien Régime. La prise de la Bastille devient un symbole fort, même si l’événement militaire lui-même reste limité. La Révolution remet en question la monarchie absolue, les privilèges et la place du citoyen. C’est l’une des dates les plus importantes pour comprendre la France moderne.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/event/French-Revolution', 2, '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),

  ('histoire-essentielle', 'le-mur-de-berlin-est-tombe-en-1989',
  'Le mur de Berlin est tombé en 1989.',
  'Sa chute symbolise la fin de la guerre froide en Europe.',
  'Construit en 1961, le mur séparait Berlin-Est et Berlin-Ouest depuis près de trente ans. Sa chute devient l’une des images les plus fortes de la fin du XXe siècle.',
  'Le mur de Berlin est construit par l’Allemagne de l’Est pour empêcher ses habitants de fuir vers l’Ouest. Pendant la guerre froide, il devient le symbole concret de la division entre le bloc soviétique et le monde occidental. En 1989, après des manifestations et un affaiblissement du régime est-allemand, les frontières s’ouvrent. Des milliers de personnes franchissent puis détruisent le mur. Cet événement annonce la réunification allemande et la fin d’un monde divisé en deux blocs.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/topic/Berlin-Wall', 3, '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),

  ('histoire-essentielle', 'le-premier-pas-sur-la-lune-a-eu-lieu-en-1969',
  'Le premier pas sur la Lune a eu lieu en 1969.',
  '1969 devient l’année où l’humain marche sur un autre monde.',
  'Neil Armstrong devient alors le premier humain à marcher sur la Lune. L’événement est suivi à la télévision par des centaines de millions de personnes dans le monde.',
  'Le 20 juillet 1969, la mission Apollo 11 réussit à poser deux astronautes sur la Lune. Neil Armstrong descend le premier, suivi par Buzz Aldrin. Cet exploit se déroule dans le contexte de la course à l’espace entre les États-Unis et l’URSS. Au-delà de la prouesse technique, l’événement devient une image culturelle immense : pour la première fois, l’humanité quitte vraiment sa planète. C’est l’un des grands repères du XXe siècle.',
  'NASA', 'https://www.nasa.gov/history/apollo-11-mission-overview/', 4, '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),

  ('histoire-essentielle', 'christophe-colomb-atteint-lamerique-en-1492',
  'Christophe Colomb atteint l’Amérique en 1492.',
  'Colomb pensait rejoindre l’Asie, pas découvrir un nouveau continent.',
  'En 1492, Christophe Colomb traverse l’Atlantique en pensant trouver une route vers l’Asie. Son voyage ouvre pourtant une nouvelle période de contacts entre l’Europe et les Amériques.',
  'Christophe Colomb part au service de la monarchie espagnole pour chercher une route maritime vers l’Asie. Lorsqu’il atteint les Caraïbes en 1492, il ne comprend pas immédiatement qu’il se trouve face à un continent inconnu des Européens. Ce voyage marque le début d’une période de conquêtes, d’échanges et de violences coloniales majeures. La date reste fondamentale, non parce qu’il “découvre” un monde vide, mais parce qu’elle transforme l’histoire mondiale.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/biography/Christopher-Columbus', 5, '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),

  ('histoire-essentielle', 'gutenberg-rend-les-livres-plus-rapides-a-produire',
  'Gutenberg a rendu les livres beaucoup plus rapides à produire.',
  'Avant l’imprimerie, copier un livre prenait un temps immense.',
  'Au XVe siècle, Gutenberg développe l’imprimerie à caractères mobiles en Europe. Au lieu de recopier chaque livre à la main, on peut composer une page avec des lettres réutilisables et l’imprimer en plusieurs exemplaires.',
  'Avant Gutenberg, les livres sont souvent copiés à la main par des scribes, ce qui demande beaucoup de temps et les rend rares et chers. Les caractères mobiles permettent de réutiliser les mêmes lettres pour produire plusieurs pages plus vite. Cette innovation ne crée pas le savoir, mais elle accélère fortement sa diffusion. Les textes religieux, scientifiques et politiques circulent davantage. C’est une étape majeure dans l’histoire de la lecture et de la culture européenne.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/technology/printing-press', 6, '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),

  ('histoire-essentielle', 'le-debarquement-de-normandie-a-eu-lieu-le-6-juin-1944',
  'Le débarquement de Normandie a eu lieu le 6 juin 1944.',
  'Le D-Day ouvre la libération de l’Europe de l’Ouest.',
  'Des milliers de soldats alliés débarquent sur les plages normandes pour ouvrir un nouveau front contre l’Allemagne nazie. L’opération devient l’un des tournants de la Seconde Guerre mondiale.',
  'Le 6 juin 1944, les forces alliées lancent une immense opération militaire sur les côtes de Normandie. L’objectif est de reprendre pied en Europe occidentale et de faire reculer l’Allemagne nazie. L’opération mobilise des soldats, des navires, des avions et une logistique gigantesque. Elle ne met pas fin immédiatement à la guerre, mais elle ouvre une étape décisive vers la libération de la France puis de l’Europe de l’Ouest.',
  'Imperial War Museums', 'https://www.iwm.org.uk/history/the-10-things-you-need-to-know-about-d-day', 7, '#f97316', 'from-[#1c1917] via-[#7c2d12] to-[#fb923c]'),

  ('cinema-culture-pop', 'le-premier-film-de-lhistoire-date-de-1888',
  'Le premier film de l’histoire date de 1888.',
  NULL,
  'C’était Roundhay Garden Scene, un film de quelques secondes montrant simplement des personnes dans un jardin. À l’époque, voir des images bouger était déjà un exploit.',
  'Roundhay Garden Scene est filmé en 1888 au Royaume-Uni par Louis Le Prince. Le film dure moins de trois secondes et montre des proches du réalisateur marchant dans un jardin. Cela peut paraître insignifiant aujourd’hui, mais capturer le mouvement était alors une prouesse technique. Le cinéma n’existait pas encore comme industrie ou art populaire. Quelques années plus tard, les projections publiques feront entrer les images animées dans la culture mondiale.',
  'Science Museum', 'https://www.sciencemuseum.org.uk/objects-and-stories/very-short-history-cinema', 8, '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),

  ('cinema-culture-pop', 'hitchcock-est-surnomme-le-maitre-du-suspense',
  'Hitchcock est surnommé le maître du suspense.',
  'Chez Hitchcock, l’attente fait souvent plus peur que le choc.',
  'Alfred Hitchcock était un réalisateur britannique du XXe siècle, connu pour des films comme Psychose, Fenêtre sur cour ou Sueurs froides. Il excellait dans l’art de faire monter la tension avant même que le danger arrive.',
  'Alfred Hitchcock est l’une des grandes figures de l’histoire du cinéma. Réalisateur britannique puis hollywoodien, il devient célèbre pour sa manière de manipuler l’attention du spectateur. Dans ses films, la peur ne vient pas seulement de ce qui arrive, mais de ce qu’on anticipe. Psychose, Fenêtre sur cour ou Sueurs froides restent des références majeures. Savoir qui est Hitchcock, c’est comprendre une base essentielle du cinéma de suspense.',
  'British Film Institute', 'https://www.bfi.org.uk/features/where-begin-alfred-hitchcock', 9, '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),

  ('cinema-culture-pop', 'pulp-fiction-est-raconte-dans-le-desordre-volontairement',
  'Pulp Fiction est raconté dans le désordre volontairement.',
  'Le spectateur doit reconstruire l’histoire lui-même.',
  'Quentin Tarantino mélange volontairement les périodes du récit. Cette structure inhabituelle donne au film un style très reconnaissable et marque fortement le cinéma des années 1990.',
  'Sorti en 1994, Pulp Fiction devient rapidement un film culte. Tarantino y raconte plusieurs histoires liées entre elles, mais sans respecter l’ordre chronologique classique. Le public doit donc relier les scènes et comprendre peu à peu comment les événements s’assemblent. Ce choix donne au film une énergie particulière et un ton très différent du cinéma hollywoodien plus traditionnel. C’est l’une des raisons pour lesquelles Pulp Fiction reste une référence de culture cinéma.',
  'Festival de Cannes', 'https://www.festival-cannes.com/en/f/pulp-fiction/', 10, '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),

  ('cinema-culture-pop', 'star-wars-etait-un-projet-trop-etrange-pour-rassurer-hollywood',
  'Star Wars était un projet trop étrange pour rassurer Hollywood.',
  'Avant de devenir culte, Star Wars inquiétait une partie de l’industrie.',
  'Dans les années 1970, l’univers imaginé par George Lucas paraît risqué : sabres laser, robots, vaisseaux, mythologie spatiale. Le film sort pourtant en 1977 et devient un phénomène mondial.',
  'Avant sa sortie, Star Wars ne ressemble pas vraiment aux succès habituels d’Hollywood. Le projet mêle science-fiction, aventure, conte mythologique et effets spéciaux ambitieux. Une partie de l’industrie comprend mal le potentiel du film, et le tournage lui-même connaît plusieurs difficultés. À sa sortie en 1977, le public répond pourtant massivement. Star Wars transforme le blockbuster moderne, les produits dérivés et la culture populaire mondiale.',
  'Lucasfilm', 'https://www.lucasfilm.com/productions/star-wars-a-new-hope/', 11, '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),

  ('cinema-culture-pop', 'jurassic-park-a-change-les-effets-speciaux-modernes',
  'Jurassic Park a changé les effets spéciaux modernes.',
  'Après Jurassic Park, les créatures numériques deviennent crédibles.',
  'Sorti en 1993, le film mélange animatroniques et images de synthèse pour donner vie aux dinosaures. Le résultat impressionne tellement qu’il change les attentes du public envers les effets spéciaux.',
  'Avant Jurassic Park, les créatures numériques existent déjà, mais elles convainquent rarement totalement le grand public. Steven Spielberg et les équipes d’Industrial Light & Magic combinent des robots réalistes avec des images générées par ordinateur. Cette combinaison donne aux dinosaures une présence très forte à l’écran. Le succès du film montre à Hollywood que le numérique peut devenir un outil central du cinéma spectaculaire. C’est un vrai tournant technique et culturel.',
  'Industrial Light & Magic', 'https://www.ilm.com/vfx/jurassic-park/', 12, '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),

  ('cinema-culture-pop', 'le-parrain-a-failli-ne-pas-avoir-marlon-brando',
  'Le Parrain a failli ne pas avoir Marlon Brando.',
  'Un acteur jugé risqué devient une légende du cinéma.',
  'Le studio doutait de Marlon Brando, considéré comme difficile à gérer. Son interprétation de Vito Corleone deviendra pourtant l’une des plus célèbres de l’histoire du cinéma.',
  'Le Parrain sort en 1972 et devient rapidement un monument du cinéma américain. Pourtant, le choix de Marlon Brando n’était pas évident pour le studio, qui craignait son comportement et son image. Francis Ford Coppola insiste pour lui confier le rôle. Brando crée alors une présence lente, grave et immédiatement reconnaissable. Ce rôle relance sa carrière et devient une référence absolue pour comprendre le cinéma des années 1970.',
  'Paramount Pictures', 'https://www.paramountmovies.com/movies/the-godfather', 13, '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),

  ('cinema-culture-pop', 'toy-story-est-le-premier-long-metrage-entierement-en-images-de-synthese',
  'Toy Story est le premier long-métrage entièrement en images de synthèse.',
  'Un film de jouets ouvre une nouvelle époque de l’animation.',
  'Sorti en 1995, Toy Story prouve qu’un film animé entièrement par ordinateur peut toucher le grand public. Après lui, l’animation numérique devient progressivement dominante.',
  'Avant Toy Story, les images de synthèse sont surtout utilisées par touches ou pour des effets spécifiques. Pixar parvient à en faire un long-métrage entier, avec une histoire simple et émotionnelle. Le film part d’une idée très accessible : et si les jouets prenaient vie quand les humains quittent la pièce ? Son succès change durablement l’industrie de l’animation. Il marque le passage vers une nouvelle manière de produire des films familiaux.',
  'Pixar', 'https://www.pixar.com/feature-films/toy-story', 14, '#ec4899', 'from-[#1f1020] via-[#831843] to-[#f472b6]'),

  ('grandes-figures', 'charlie-chaplin-est-devenu-mondialement-celebre-sans-presque-parler',
  'Charlie Chaplin est devenu mondialement célèbre sans presque parler.',
  'Ses gestes traversaient les langues.',
  'Charlie Chaplin était un acteur et réalisateur britannique du cinéma muet. Avec son personnage de Charlot, sa silhouette, ses gestes et son visage suffisaient à faire comprendre ses histoires partout dans le monde.',
  'Charlie Chaplin devient célèbre au début du XXe siècle, à l’époque où le cinéma est encore muet. Son personnage de Charlot, avec sa moustache, sa canne et sa démarche reconnaissable, devient une figure universelle. Comme ses films reposent surtout sur le corps et l’expression, ils peuvent être compris dans de nombreux pays sans traduction. Chaplin est important parce qu’il montre que le cinéma peut émouvoir, faire rire et critiquer la société sans paroles.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/biography/Charlie-Chaplin', 15, '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),

  ('grandes-figures', 'einstein-a-change-notre-maniere-de-penser-le-temps-et-lespace',
  'Einstein a changé notre manière de penser le temps et l’espace.',
  'Même sans comprendre ses équations, on peut retenir son idée centrale.',
  'Albert Einstein était un physicien du XXe siècle. Il est surtout connu pour la relativité, qui a bouleversé notre façon de comprendre le temps, l’espace, la lumière et la gravité.',
  'Einstein n’est pas seulement une image de “génie” avec des cheveux en bataille. Ses travaux ont changé la physique moderne, notamment avec la relativité restreinte puis générale. L’idée essentielle est que le temps et l’espace ne sont pas aussi fixes qu’on l’imaginait. Ils dépendent notamment du mouvement et de la gravité. Ses découvertes influencent encore l’astronomie, la technologie et notre vision de l’univers.',
  'Nobel Prize', 'https://www.nobelprize.org/prizes/physics/1921/einstein/facts/', 16, '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),

  ('grandes-figures', 'marie-curie-a-recu-deux-prix-nobel',
  'Marie Curie a reçu deux prix Nobel.',
  'Elle reste l’une des rares figures récompensées dans deux sciences différentes.',
  'Marie Curie était une scientifique franco-polonaise spécialisée dans la radioactivité. Elle reçoit un Nobel de physique puis un Nobel de chimie, ce qui reste exceptionnel dans l’histoire des sciences.',
  'Marie Curie travaille avec Pierre Curie sur la radioactivité, un domaine encore nouveau à son époque. Elle reçoit le prix Nobel de physique en 1903, puis celui de chimie en 1911. Son parcours est remarquable à la fois scientifiquement et socialement, car les femmes sont alors très peu reconnues dans le monde académique. Elle devient une figure majeure de l’histoire des sciences. Son nom reste associé au radium, à la recherche et à la persévérance.',
  'Nobel Prize', 'https://www.nobelprize.org/prizes/physics/1903/marie-curie/facts/', 17, '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),

  ('grandes-figures', 'napoleon-netait-probablement-pas-si-petit',
  'Napoléon n’était probablement pas si petit.',
  'Sa petite taille est surtout une légende tenace.',
  'Napoléon Bonaparte était un général puis empereur français du début du XIXe siècle. Sa réputation d’homme très petit viendrait surtout de caricatures anglaises et de confusions entre anciennes mesures.',
  'Napoléon reste l’une des figures les plus connues de l’histoire française, à la fois pour ses victoires militaires, son pouvoir impérial et son héritage administratif. L’idée qu’il était très petit est pourtant largement exagérée. Sa taille était plutôt normale pour son époque. Les caricatures britanniques l’ont souvent représenté minuscule pour le ridiculiser. Ce détail montre comment la propagande peut façonner durablement l’image d’un personnage historique.',
  'Fondation Napoléon', 'https://www.napoleon.org/histoire-des-2-empires/articles/napoleon-etait-il-petit/', 18, '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),

  ('grandes-figures', 'rosa-parks-na-pas-seulement-refuse-de-ceder-sa-place',
  'Rosa Parks n’a pas seulement refusé de céder sa place.',
  'Un refus dans un bus déclenche un mouvement immense.',
  'Rosa Parks était une militante américaine des droits civiques. En 1955, son refus de céder sa place dans un bus de Montgomery devient le point de départ d’un boycott massif.',
  'Rosa Parks est souvent résumée à un geste simple : rester assise dans un bus. Mais ce geste s’inscrit dans un combat organisé contre la ségrégation raciale aux États-Unis. Après son arrestation, les habitants noirs de Montgomery lancent un boycott des bus qui dure plus d’un an. Martin Luther King y gagne une visibilité nationale. Rosa Parks devient ainsi une figure centrale du mouvement des droits civiques.',
  'National Archives', 'https://www.archives.gov/education/lessons/rosa-parks', 19, '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),

  ('grandes-figures', 'leonard-de-vinci-etait-autant-inventeur-quartiste',
  'Léonard de Vinci était autant inventeur qu’artiste.',
  'La Joconde n’est qu’une partie de son génie curieux.',
  'Léonard de Vinci était un artiste, ingénieur et savant italien de la Renaissance. On connaît surtout La Joconde, mais ses carnets montrent aussi des machines, des études du corps et des idées très en avance.',
  'Léonard de Vinci incarne parfaitement l’esprit de la Renaissance : observer, comprendre, dessiner, inventer. Il peint des œuvres majeures comme La Joconde et La Cène, mais il s’intéresse aussi à l’anatomie, à l’eau, au vol, aux machines et aux armes. Ses carnets montrent une curiosité immense pour le fonctionnement du monde. C’est pour cela qu’il est souvent présenté comme un génie universel, pas seulement comme un peintre.',
  'Musée du Louvre', 'https://www.louvre.fr/decouvrir/le-palais/la-joconde', 20, '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),

  ('grandes-figures', 'nelson-mandela-a-passe-27-ans-en-prison',
  'Nelson Mandela a passé 27 ans en prison.',
  'Mandela passe de prisonnier politique à symbole mondial.',
  'Nelson Mandela était un militant puis président sud-africain. Emprisonné pendant 27 ans pour son combat contre l’apartheid, il devient ensuite une figure mondiale de la réconciliation.',
  'Nelson Mandela lutte contre l’apartheid, un système de ségrégation raciale imposé en Afrique du Sud. Son engagement lui vaut une longue incarcération, notamment sur l’île de Robben Island. Libéré en 1990, il participe aux négociations qui mettent fin à l’apartheid. En 1994, il devient le premier président noir du pays. Son parcours reste associé à la résistance, au pardon politique et à la reconstruction nationale.',
  'Nelson Mandela Foundation', 'https://www.nelsonmandela.org/content/page/biography', 21, '#8b5cf6', 'from-[#17132a] via-[#4c1d95] to-[#a78bfa]'),

  ('arts-litterature', 'van-gogh-na-connu-la-celebrite-quapres-sa-mort',
  'Van Gogh n’a connu la célébrité qu’après sa mort.',
  'L’un des peintres les plus célèbres du monde a vécu presque inconnu.',
  'Vincent van Gogh était un peintre néerlandais du XIXe siècle. Aujourd’hui, ses tableaux sont parmi les plus connus au monde, mais il a vécu pauvrement et n’a connu qu’une reconnaissance très limitée de son vivant.',
  'Van Gogh peint des œuvres devenues célèbres comme La Nuit étoilée, Les Tournesols ou sa série d’autoportraits. Son style, fait de couleurs intenses et de coups de pinceau visibles, est aujourd’hui immédiatement reconnaissable. Pourtant, il souffre toute sa vie de difficultés financières et psychologiques. Sa reconnaissance arrive surtout après sa mort, grâce notamment au travail de conservation et de promotion de son entourage. Son histoire symbolise le génie artistique ignoré de son époque.',
  'Van Gogh Museum', 'https://www.vangoghmuseum.nl/en/art-and-stories/stories/5-things-you-need-to-know-about-vincent-van-gogh', 22, '#06b6d4', 'from-[#071a20] via-[#164e63] to-[#67e8f9]'),

  ('arts-litterature', 'picasso-savait-dessiner-de-maniere-tres-realiste',
  'Picasso savait dessiner de manière très réaliste.',
  'Son style déformé était un choix, pas une limite.',
  'Pablo Picasso était un artiste espagnol du XXe siècle. Avant ses œuvres cubistes, il maîtrisait déjà le dessin classique, ce qui montre que ses formes étranges étaient une décision artistique.',
  'Picasso est souvent associé aux visages déformés et aux formes géométriques du cubisme. Pourtant, il apprend très tôt à dessiner de manière académique et réaliste. Son évolution montre qu’il ne cherche pas à “mal dessiner”, mais à représenter autrement le monde. Avec Georges Braque, il participe à inventer le cubisme, qui montre plusieurs angles d’un sujet en même temps. Comprendre cela rend son œuvre beaucoup moins intimidante.',
  'Musée Picasso Paris', 'https://www.museepicassoparis.fr/fr/pablo-picasso', 23, '#06b6d4', 'from-[#071a20] via-[#164e63] to-[#67e8f9]'),

  ('arts-litterature', 'la-joconde-est-celebre-aussi-parce-quelle-a-ete-volee',
  'La Joconde est célèbre aussi parce qu’elle a été volée.',
  'Un vol a transformé un tableau en phénomène mondial.',
  'En 1911, La Joconde disparaît du Louvre pendant plus de deux ans. L’affaire fait la une des journaux et contribue à transformer le tableau de Léonard de Vinci en icône mondiale.',
  'Avant son vol, La Joconde est déjà une œuvre admirée, mais elle n’a pas encore son statut de star mondiale. En 1911, un ancien employé du Louvre la dérobe et le musée se retrouve au centre d’une affaire très médiatisée. Le public vient même voir l’emplacement vide du tableau. Quand l’œuvre est retrouvée, sa célébrité a changé d’échelle. Ce fait montre comment un événement médiatique peut transformer une œuvre d’art en mythe populaire.',
  'Musée du Louvre', 'https://www.louvre.fr/decouvrir/le-palais/la-joconde', 24, '#06b6d4', 'from-[#071a20] via-[#164e63] to-[#67e8f9]'),

  ('arts-litterature', 'frankenstein-a-ete-ecrit-par-mary-shelley-a-seulement-18-ans',
  'Frankenstein a été écrit par Mary Shelley à seulement 18 ans.',
  'Le roman pose déjà la question des créations qu’on ne maîtrise plus.',
  'Mary Shelley était une écrivaine britannique du XIXe siècle. Dans Frankenstein, elle imagine une créature fabriquée par un scientifique, mais interroge surtout la responsabilité de l’humain face à ce qu’il crée.',
  'Frankenstein naît dans un contexte littéraire étonnant : Mary Shelley participe à un défi d’écriture autour d’histoires effrayantes. Son roman dépasse rapidement la simple histoire de monstre. Il parle de solitude, d’ambition scientifique, de rejet et de responsabilité morale. Beaucoup de débats modernes sur la technologie ou l’intelligence artificielle retrouvent une question proche : que se passe-t-il quand une création échappe à son créateur ?',
  'British Library', 'https://www.bl.uk/romantics-and-victorians/articles/frankenstein-the-creation-of-a-monster', 25, '#06b6d4', 'from-[#071a20] via-[#164e63] to-[#67e8f9]'),

  ('arts-litterature', 'le-petit-prince-est-lun-des-livres-les-plus-traduits-au-monde',
  'Le Petit Prince est l’un des livres les plus traduits au monde.',
  'Un conte simple cache une réflexion très adulte.',
  'Écrit par Antoine de Saint-Exupéry, Le Petit Prince ressemble à un conte pour enfants. Mais il parle aussi de solitude, d’amitié, d’amour et du regard parfois absurde des adultes.',
  'Le Petit Prince paraît en 1943, pendant l’exil de Saint-Exupéry. Son style est simple, mais ses thèmes sont profonds. Le voyage du personnage de planète en planète permet de critiquer les comportements humains : vanité, pouvoir, obsession des chiffres ou incapacité à aimer simplement. C’est cette double lecture qui rend le livre accessible aux enfants et précieux pour les adultes. Il est devenu une référence mondiale de la littérature française.',
  'Fondation Antoine de Saint-Exupéry', 'https://www.fondation-antoine-de-saint-exupery.org/', 26, '#06b6d4', 'from-[#071a20] via-[#164e63] to-[#67e8f9]'),

  ('science-accessible', 'ton-cerveau-reecrit-legerement-tes-souvenirs',
  'Ton cerveau réécrit légèrement tes souvenirs.',
  'Se souvenir, ce n’est pas relire une vidéo intacte.',
  'Quand tu te rappelles quelque chose, ton cerveau reconstruit le souvenir au lieu de simplement le rejouer comme un fichier. C’est pourquoi un souvenir peut évoluer avec le temps.',
  'La mémoire humaine n’est pas un enregistrement parfait. Quand un souvenir revient, le cerveau réassemble des éléments : images, émotions, contexte et détails appris ensuite. Cette reconstruction peut introduire de petites modifications. Cela explique pourquoi deux personnes peuvent se souvenir différemment du même événement. C’est aussi pour cela que nos souvenirs personnels semblent parfois très vrais, même lorsqu’ils ont changé.',
  'American Psychological Association', 'https://www.apa.org/topics/memory', 27, '#22c55e', 'from-[#061a12] via-[#14532d] to-[#86efac]'),

  ('science-accessible', 'ton-cerveau-ignore-une-partie-de-ce-que-tes-yeux-voient',
  'Ton cerveau ignore une partie de ce que tes yeux voient.',
  'Voir ne signifie pas forcément remarquer.',
  'Le cerveau trie constamment les informations pour éviter la surcharge. C’est pour cela qu’un détail pourtant visible peut passer totalement inaperçu si ton attention est ailleurs.',
  'Nos yeux captent une grande quantité d’informations, mais le cerveau ne peut pas tout traiter consciemment. Il sélectionne ce qui semble utile selon l’objectif du moment. Si tu cherches tes clés, tu peux ne pas remarquer un objet pourtant évident juste à côté. Ce mécanisme est très utile pour rester concentré, mais il explique aussi certaines erreurs de perception. Notre vision est donc moins neutre qu’on l’imagine.',
  'American Psychological Association', 'https://www.apa.org/topics/sensation-perception', 28, '#22c55e', 'from-[#061a12] via-[#14532d] to-[#86efac]'),

  ('science-accessible', 'le-sommeil-aide-ton-cerveau-a-trier-la-journee',
  'Le sommeil aide ton cerveau à trier la journée.',
  'Dormir, c’est aussi ranger les souvenirs.',
  'Pendant le sommeil, le cerveau consolide certaines informations et en laisse d’autres de côté. Il ne sert donc pas seulement à récupérer physiquement.',
  'Le sommeil joue un rôle important dans la mémoire et l’apprentissage. Après une journée, le cerveau doit traiter une grande quantité d’informations. Certaines sont renforcées, d’autres deviennent moins importantes. C’est pour cela qu’une bonne nuit peut aider à mieux retenir une leçon, un geste ou une expérience. Le sommeil agit comme un temps de rangement invisible, essentiel au fonctionnement mental.',
  'NIH News in Health', 'https://newsinhealth.nih.gov/2013/04/benefits-slumber', 29, '#22c55e', 'from-[#061a12] via-[#14532d] to-[#86efac]'),

  ('science-accessible', 'les-bananes-sont-legerement-radioactives',
  'Les bananes sont légèrement radioactives.',
  'Un fruit banal contient une radioactivité naturelle inoffensive.',
  'Les bananes contiennent naturellement du potassium, dont une infime partie émet de faibles radiations. La quantité est sans danger, mais l’idée surprend parce qu’il s’agit d’un fruit du quotidien.',
  'La radioactivité n’est pas uniquement liée aux centrales nucléaires ou aux accidents. Certains éléments naturels en émettent de très petites quantités. Les bananes contiennent du potassium, indispensable au corps, et une toute petite fraction de ce potassium est naturellement radioactive. Cela ne rend pas les bananes dangereuses. Ce fait est intéressant parce qu’il montre que le mot “radioactif” peut désigner des réalités très différentes selon les doses.',
  'United States Environmental Protection Agency', 'https://www.epa.gov/radtown/natural-radioactivity-food', 30, '#22c55e', 'from-[#061a12] via-[#14532d] to-[#86efac]'),

  ('science-accessible', 'les-pieuvres-ont-trois-coeurs',
  'Les pieuvres ont trois cœurs.',
  'Deux cœurs aident à respirer, un autre alimente le corps.',
  'Chez la pieuvre, deux cœurs envoient le sang vers les branchies, tandis qu’un troisième l’envoie vers le reste du corps. C’est l’un des détails qui rend cet animal si différent de nous.',
  'Les pieuvres font partie des animaux les plus étonnants des océans. Leur corps fonctionne très différemment de celui des mammifères. Deux de leurs cœurs servent principalement à faire passer le sang par les branchies, où il se charge en oxygène. Le troisième envoie ensuite le sang vers les organes. Ce système accompagne un animal très souple, intelligent et capable de comportements complexes.',
  'Smithsonian Ocean', 'https://ocean.si.edu/ocean-life/invertebrates/octopus', 31, '#22c55e', 'from-[#061a12] via-[#14532d] to-[#86efac]'),

  ('inventions-technologie', 'le-premier-iphone-ne-permettait-pas-de-copier-coller',
  'Le premier iPhone ne permettait pas de copier-coller.',
  'Même révolutionnaire, le premier iPhone était incomplet.',
  'Présenté par Steve Jobs en 2007, le premier iPhone impressionne par son écran tactile et sa simplicité. Pourtant, certaines fonctions aujourd’hui évidentes, comme le copier-coller, n’existaient pas encore.',
  'Avant l’iPhone, beaucoup de téléphones reposent sur des claviers physiques et des menus moins fluides. Apple propose un appareil presque entièrement contrôlé au doigt, avec une navigation beaucoup plus intuitive. Le produit n’est pourtant pas complet : il manque plusieurs fonctions devenues banales plus tard. Son succès montre qu’une innovation peut transformer les usages même en commençant avec des limites. L’important était surtout l’expérience globale.',
  'Apple', 'https://www.apple.com/newsroom/2007/01/09Apple-Reinvents-the-Phone-with-iPhone/', 32, '#3b82f6', 'from-[#071426] via-[#1d4ed8] to-[#93c5fd]'),

  ('inventions-technologie', 'internet-vient-dun-reseau-de-recherche-avant-de-devenir-public',
  'Internet vient d’un réseau de recherche avant de devenir public.',
  'Avant le web grand public, Internet reliait surtout des institutions.',
  'Internet trouve ses origines dans des réseaux créés pour connecter des ordinateurs entre universités, chercheurs et institutions. Il ne devient un outil du quotidien que bien plus tard.',
  'Internet ne naît pas directement comme un réseau social, un moteur de recherche ou un outil de divertissement. Ses origines viennent de projets visant à faire communiquer des ordinateurs à distance, notamment dans des milieux de recherche. Le web, les navigateurs et les usages grand public arrivent ensuite. Cette évolution explique pourquoi Internet est à la fois une infrastructure technique, un espace culturel et un outil économique majeur.',
  'Internet Society', 'https://www.internetsociety.org/internet/history-internet/brief-history-internet/', 33, '#3b82f6', 'from-[#071426] via-[#1d4ed8] to-[#93c5fd]'),

  ('inventions-technologie', 'le-qr-code-a-ete-invente-pour-suivre-des-pieces-automobiles',
  'Le QR code a été inventé pour suivre des pièces automobiles.',
  'Un outil d’usine est devenu un geste du quotidien.',
  'Créé au Japon dans les années 1990, le QR code servait d’abord à identifier rapidement des composants dans l’industrie automobile. Il est ensuite devenu courant pour les menus, billets et paiements.',
  'Le QR code est inventé par Denso Wave pour répondre à un problème très concret : suivre plus facilement des pièces dans les chaînes de production. Contrairement au code-barres classique, il peut contenir plus d’informations et être lu rapidement. Pendant longtemps, il reste surtout industriel. Avec les smartphones, il devient un outil du quotidien. Scanner un carré noir et blanc est désormais un geste culturel banal.',
  'DENSO Wave', 'https://www.qrcode.com/en/history/', 34, '#3b82f6', 'from-[#071426] via-[#1d4ed8] to-[#93c5fd]'),

  ('inventions-technologie', 'bluetooth-porte-le-nom-dun-roi-viking',
  'Bluetooth porte le nom d’un roi viking.',
  'Une technologie sans fil cache une référence médiévale.',
  'Le nom vient de Harald “Bluetooth”, un roi scandinave connu pour avoir uni des territoires. Les créateurs de la technologie voulaient rappeler l’idée de connecter différents appareils.',
  'Bluetooth paraît être un nom purement technique, mais il vient d’une référence historique. Harald Bluetooth, roi du Danemark au Xe siècle, est associé à l’unification de peuples scandinaves. Les ingénieurs ont repris cette image pour une technologie censée faire communiquer des appareils différents. Même le logo Bluetooth combine deux anciennes runes liées à son nom. C’est un bon exemple de culture cachée dans un objet numérique banal.',
  'Bluetooth SIG', 'https://www.bluetooth.com/about-us/bluetooth-origin/', 35, '#3b82f6', 'from-[#071426] via-[#1d4ed8] to-[#93c5fd]'),

  ('inventions-technologie', 'la-photographie-a-dabord-demande-de-tres-longs-temps-de-pose',
  'La photographie a d’abord demandé de très longs temps de pose.',
  'Les vieux portraits sont sérieux pour une raison technique.',
  'Les premières photographies nécessitaient parfois plusieurs minutes d’immobilité. C’est l’une des raisons pour lesquelles les personnes posaient souvent avec un visage fixe et très sérieux.',
  'Au début de la photographie, les appareils ne captent pas l’image aussi vite qu’aujourd’hui. Il faut rester immobile longtemps pour éviter que le portrait soit flou. Sourire pendant plusieurs minutes est difficile, et les normes sociales de l’époque valorisent aussi une posture sérieuse. Les portraits anciens donnent donc une impression de gravité qui vient à la fois de la technique et de la culture. Cela rappelle que nos images dépendent toujours des outils disponibles.',
  'National Geographic', 'https://www.nationalgeographic.com/photography/article/milestones-photography', 36, '#3b82f6', 'from-[#071426] via-[#1d4ed8] to-[#93c5fd]'),

  ('quotidien-societe', 'le-week-end-de-deux-jours-sest-surtout-generalise-au-xxe-siecle',
  'Le week-end de deux jours s’est surtout généralisé au XXe siècle.',
  'Avoir deux jours de repos est une conquête sociale récente.',
  'Pendant longtemps, beaucoup de travailleurs n’avaient qu’un seul jour de repos, souvent le dimanche. Le samedi libre se développe progressivement avec la réduction du temps de travail et les luttes sociales.',
  'Au XIXe siècle, le travail occupe souvent six jours par semaine, parfois davantage selon les métiers. Le dimanche reste longtemps le principal jour de repos, lié aussi aux pratiques religieuses. Au début du XXe siècle, les syndicats et les mouvements ouvriers revendiquent davantage de temps libre. Le samedi après-midi puis le samedi entier deviennent progressivement des temps de repos dans plusieurs pays industrialisés. Le week-end tel qu’on le connaît n’a donc rien de naturel : il s’est construit historiquement.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/topic/week', 37, '#f59e0b', 'from-[#1c1608] via-[#92400e] to-[#fbbf24]'),

  ('quotidien-societe', 'les-jeans-etaient-dabord-des-vetements-de-travail',
  'Les jeans étaient d’abord des vêtements de travail.',
  'Le jean passe de l’atelier au vêtement universel.',
  'Leur tissu solide convenait aux ouvriers, mineurs et chercheurs d’or. Avec le temps, le jean quitte le monde du travail pour devenir l’un des vêtements les plus portés au monde.',
  'Le jean est associé aujourd’hui à la mode, à la jeunesse ou au quotidien. À l’origine, il répond surtout à un besoin pratique : disposer d’un pantalon résistant pour des travaux physiques. Levi Strauss et Jacob Davis participent à populariser ce vêtement renforcé au XIXe siècle. Plus tard, le cinéma, la musique et la culture populaire lui donnent une image rebelle puis universelle. Le jean montre comment un objet utilitaire peut devenir un symbole culturel.',
  'Levi Strauss & Co.', 'https://www.levistrauss.com/2014/07/04/the-history-of-denim/', 38, '#f59e0b', 'from-[#1c1608] via-[#92400e] to-[#fbbf24]'),

  ('quotidien-societe', 'les-talons-hauts-etaient-dabord-portes-par-des-hommes',
  'Les talons hauts étaient d’abord portés par des hommes.',
  'Les talons étaient liés au cheval avant la mode féminine.',
  'Les talons servaient notamment aux cavaliers pour mieux tenir les étriers. Avec le temps, ils deviennent un signe de statut, puis un élément de mode surtout associé aux femmes.',
  'Aujourd’hui, les talons hauts sont généralement perçus comme féminins. Pourtant, leur histoire est plus complexe. Dans certaines cultures, ils sont d’abord liés à l’équitation et au pouvoir masculin. Porter des talons peut aussi marquer un rang social élevé, car cela signale qu’on ne travaille pas physiquement. La mode transforme ensuite leur signification. C’est un exemple clair de code vestimentaire qui change totalement de sens avec le temps.',
  'Victoria and Albert Museum', 'https://www.vam.ac.uk/articles/a-history-of-shoes', 39, '#f59e0b', 'from-[#1c1608] via-[#92400e] to-[#fbbf24]'),

  ('quotidien-societe', 'les-cartes-du-monde-deforment-la-taille-reelle-des-pays',
  'Les cartes du monde déforment la taille réelle des pays.',
  'Une carte plate ne peut pas respecter toutes les tailles.',
  'Sur certaines cartes, le Groenland semble presque aussi grand que l’Afrique. En réalité, l’Afrique est environ 14 fois plus vaste : la projection d’une sphère sur du plat crée forcément des déformations.',
  'La Terre est ronde, mais une carte est plate. Pour passer de l’une à l’autre, il faut forcément déformer quelque chose : les tailles, les formes, les distances ou les angles. La projection de Mercator, très utilisée, agrandit beaucoup les régions proches des pôles. Cela donne parfois une vision faussée de l’importance réelle des continents. Comprendre cela aide à lire les cartes avec plus de recul.',
  'National Geographic', 'https://education.nationalgeographic.org/resource/map-projections/', 40, '#f59e0b', 'from-[#1c1608] via-[#92400e] to-[#fbbf24]'),

  ('quotidien-societe', 'les-supermarches-sont-penses-pour-guider-tes-choix',
  'Les supermarchés sont pensés pour guider tes choix.',
  'Les rayons ne sont pas organisés au hasard.',
  'L’emplacement des produits, les promotions et les parcours en magasin sont conçus pour rendre certains achats plus visibles ou plus tentants.',
  'Un supermarché n’est pas seulement un lieu où les produits sont rangés de manière pratique. Les marques et les enseignes réfléchissent à la visibilité, au passage, à la hauteur des yeux et aux achats impulsifs. Les produits essentiels peuvent être placés de façon à faire traverser plusieurs rayons. Les promotions attirent l’attention, même quand l’économie réelle est limitée. Ce fait aide à comprendre que l’espace commercial influence nos décisions.',
  'NielsenIQ', 'https://nielseniq.com/global/en/insights/', 41, '#f59e0b', 'from-[#1c1608] via-[#92400e] to-[#fbbf24]'),

  ('mots-origines', 'le-mot-robot-vient-dun-mot-lie-au-travail-force',
  'Le mot robot vient d’un mot lié au travail forcé.',
  'À l’origine, le robot est imaginé comme un travailleur artificiel.',
  'Le mot apparaît dans une pièce tchèque de 1920. Il vient d’une racine liée au travail pénible ou forcé, ce qui rappelle que les premiers robots étaient pensés comme des serviteurs fabriqués.',
  'Le mot “robot” est popularisé par la pièce R.U.R. de Karel Čapek. Dans cette œuvre, les robots ne sont pas d’abord des machines métalliques comme dans la science-fiction moderne, mais des êtres artificiels créés pour travailler à la place des humains. L’origine du mot montre donc une inquiétude ancienne : que se passe-t-il quand on fabrique des travailleurs sans liberté ? C’est une question encore actuelle à l’heure de l’automatisation.',
  'Science Museum', 'https://www.sciencemuseum.org.uk/objects-and-stories/robots/brief-history-robots', 42, '#14b8a6', 'from-[#06221f] via-[#0f766e] to-[#5eead4]'),

  ('mots-origines', 'le-mot-salaire-est-lie-au-sel',
  'Le mot salaire est lié au sel.',
  'Le salaire garde la trace d’une valeur ancienne : le sel.',
  'Le mot vient du latin salarium, lié au sel ou à une allocation permettant d’en acheter. Dans l’Antiquité, le sel avait une valeur importante, notamment parce qu’il servait à conserver les aliments.',
  'Aujourd’hui, le sel est un produit banal et peu coûteux. Dans l’Antiquité, il est beaucoup plus précieux, car il sert à conserver la nourriture, assaisonner et maintenir certains équilibres alimentaires. Le mot latin salarium est associé à cette importance économique. L’origine du mot “salaire” rappelle donc qu’une chose très simple aujourd’hui pouvait autrefois représenter une vraie richesse.',
  'Dictionnaire de l’Académie française', 'https://www.dictionnaire-academie.fr/article/A9S0151', 43, '#14b8a6', 'from-[#06221f] via-[#0f766e] to-[#5eead4]'),

  ('mots-origines', 'le-mot-boycott-vient-du-nom-dun-homme',
  'Le mot boycott vient du nom d’un homme.',
  'Un nom propre est devenu un mot de refus collectif.',
  'Charles Boycott était un gestionnaire irlandais du XIXe siècle. Des habitants ont refusé de travailler avec lui ou de lui rendre service, et son nom est devenu un mot utilisé dans plusieurs langues.',
  'Le boycott est aujourd’hui une stratégie connue : refuser d’acheter, de participer ou de collaborer pour faire pression. À l’origine, le mot vient d’un conflit social en Irlande dans les années 1880. Charles Boycott se retrouve isolé par une communauté qui refuse tout échange avec lui. L’affaire devient célèbre dans la presse. Son nom finit par désigner une méthode de protestation encore très utilisée aujourd’hui.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/topic/boycott', 44, '#14b8a6', 'from-[#06221f] via-[#0f766e] to-[#5eead4]'),

  ('mots-origines', 'le-mot-sandwich-vient-dun-comte-anglais',
  'Le mot sandwich vient d’un comte anglais.',
  'Un nom de noble est devenu celui d’un repas mondial.',
  'Le mot viendrait du comte de Sandwich, un aristocrate britannique du XVIIIe siècle. Il aurait popularisé l’idée de manger de la viande entre deux tranches de pain pour ne pas interrompre ses activités.',
  'L’histoire exacte du sandwich est en partie légendaire, mais elle reste très racontable. Le comte de Sandwich aurait aimé manger sans quitter sa table de jeu ou de travail. Demander de la viande entre deux morceaux de pain devient alors associé à son nom. Le plus intéressant est de voir comment un nom propre devient un mot courant dans de nombreuses langues. Un repas très banal cache donc une petite histoire sociale.',
  'Oxford English Dictionary', 'https://www.oed.com/', 45, '#14b8a6', 'from-[#06221f] via-[#0f766e] to-[#5eead4]'),

  ('geographie-monde', 'istanbul-est-a-cheval-sur-deux-continents',
  'Istanbul est à cheval sur deux continents.',
  'Une partie de la ville est en Europe, l’autre en Asie.',
  'Le détroit du Bosphore sépare la partie européenne et la partie asiatique d’Istanbul. Cette position explique pourquoi la ville a longtemps été un carrefour entre plusieurs mondes.',
  'Istanbul a porté plusieurs noms et plusieurs rôles historiques : Byzance, Constantinople, puis Istanbul. Sa position entre Europe et Asie lui donne une importance stratégique exceptionnelle. Elle contrôle un passage entre la mer Noire et la Méditerranée. Cette situation a favorisé les échanges commerciaux, militaires et culturels pendant des siècles. Comprendre Istanbul, c’est comprendre comment la géographie peut donner un destin mondial à une ville.',
  'Encyclopaedia Britannica', 'https://www.britannica.com/place/Istanbul', 46, '#84cc16', 'from-[#101a08] via-[#3f6212] to-[#bef264]'),

  ('geographie-monde', 'lantarctique-est-un-desert',
  'L’Antarctique est un désert.',
  'Un désert se définit surtout par le manque de précipitations.',
  'Même couvert de glace, l’Antarctique reçoit très peu de pluie ou de neige. Un désert n’est donc pas forcément chaud : c’est avant tout un endroit très sec.',
  'Dans l’imaginaire courant, un désert est souvent un paysage de sable et de chaleur. Mais scientifiquement, ce qui définit surtout un désert, c’est la faiblesse des précipitations. L’Antarctique est immense, glacé et presque entièrement blanc, mais il reçoit très peu d’eau sous forme de neige. Cela en fait l’un des plus grands déserts du monde. Ce fait aide à corriger une idée simple mais très répandue.',
  'National Geographic', 'https://education.nationalgeographic.org/resource/desert/', 47, '#84cc16', 'from-[#101a08] via-[#3f6212] to-[#bef264]'),

  ('geographie-monde', 'lafrique-est-beaucoup-plus-grande-quelle-ne-parait-sur-certaines-cartes',
  'L’Afrique est beaucoup plus grande qu’elle ne paraît sur certaines cartes.',
  'Les cartes classiques sous-estiment souvent sa taille réelle.',
  'À cause de certaines projections, les régions proches des pôles semblent agrandies. En réalité, l’Afrique est si vaste qu’elle peut contenir plusieurs grands pays et régions du monde réunis.',
  'Beaucoup de cartes scolaires utilisent des projections qui déforment les tailles. L’Afrique y paraît parfois moins impressionnante qu’elle ne l’est réellement. Pourtant, le continent est immense : sa surface dépasse largement celle des États-Unis, de la Chine ou de l’Europe occidentale pris séparément. Cette différence montre que les cartes ne sont jamais neutres. Elles influencent notre perception du monde.',
  'National Geographic', 'https://education.nationalgeographic.org/resource/map-projections/', 48, '#84cc16', 'from-[#101a08] via-[#3f6212] to-[#bef264]'),

  ('musique-culture', 'le-hip-hop-est-ne-dans-le-bronx-dans-les-annees-1970',
  'Le hip-hop est né dans le Bronx dans les années 1970.',
  'Une culture de quartier est devenue un mouvement mondial.',
  'Au départ, le hip-hop rassemble musique, danse, graffiti et art de la parole. Né dans un contexte urbain difficile, il devient ensuite l’un des mouvements culturels les plus influents du monde.',
  'Le hip-hop naît dans le Bronx, à New York, dans les années 1970. Il ne se limite pas au rap : il inclut aussi le DJing, le breakdance, le graffiti et une manière de raconter la vie urbaine. Cette culture donne une voix à des quartiers souvent marginalisés. Avec le temps, elle devient mondiale et influence la musique, la mode, le langage et les attitudes. Comprendre le hip-hop, c’est comprendre une grande partie de la culture contemporaine.',
  'Smithsonian Music', 'https://music.si.edu/spotlight/hip-hop', 49, '#ef4444', 'from-[#220b0b] via-[#991b1b] to-[#fca5a5]'),

  ('musique-culture', 'beethoven-a-compose-alors-quil-devenait-sourd',
  'Beethoven a composé alors qu’il devenait sourd.',
  'Il crée de la musique alors que son audition disparaît.',
  'Ludwig van Beethoven était un compositeur allemand du tournant des XVIIIe et XIXe siècles. Sa perte d’audition rend son parcours encore plus impressionnant, car il compose certaines œuvres majeures alors qu’il entend de moins en moins.',
  'Beethoven est l’un des grands noms de la musique classique, connu notamment pour ses symphonies et ses sonates. Sa surdité progressive commence alors qu’il est encore en activité. Pour un musicien, perdre l’audition est une épreuve immense. Pourtant, Beethoven continue de composer en s’appuyant sur sa mémoire musicale, sa technique et son imagination sonore. Son histoire est devenue un symbole de création malgré l’obstacle.',
  'Beethoven-Haus Bonn', 'https://www.beethoven.de/en/beethoven', 50, '#ef4444', 'from-[#220b0b] via-[#991b1b] to-[#fca5a5]')
)
INSERT INTO public.facts (
  category_id,
  slug,
  title,
  hook,
  content,
  long_content,
  source,
  source_url,
  status,
  published_at,
  display_order,
  accent_color,
  tone
)
SELECT
  c.id,
  fs.slug,
  fs.title,
  fs.hook,
  fs.content,
  fs.long_content,
  fs.source,
  fs.source_url,
  'published',
  now(),
  fs.display_order,
  fs.accent_color,
  fs.tone
FROM fact_seed fs
JOIN public.categories c ON c.slug = fs.category_slug
ON CONFLICT (slug) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  title = EXCLUDED.title,
  hook = EXCLUDED.hook,
  content = EXCLUDED.content,
  long_content = EXCLUDED.long_content,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  status = EXCLUDED.status,
  published_at = COALESCE(public.facts.published_at, EXCLUDED.published_at),
  display_order = EXCLUDED.display_order,
  accent_color = EXCLUDED.accent_color,
  tone = EXCLUDED.tone,
  updated_at = now();

COMMIT;
