-- Seed Velora : catégories + 100 faits publiés
-- À exécuter dans Supabase SQL Editor.
-- La requête est idempotente pour les catégories et évite de réinsérer un fait si son slug existe déjà.

BEGIN;

WITH category_seed(slug, name, accent_color, tone) AS (
VALUES
  ($$histoire-essentielle$$, $$Histoire essentielle$$, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$cinema-culture$$, $$Cinéma & culture pop$$, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$grandes-figures$$, $$Grandes figures$$, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$arts-litterature$$, $$Arts & littérature$$, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$science-accessible$$, $$Science accessible$$, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$inventions-technologie$$, $$Inventions & technologie$$, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$quotidien-cache$$, $$Quotidien caché$$, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$mots-origines$$, $$Mots & origines$$, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$monde-geographie$$, $$Monde & géographie$$, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$musique-culture$$, $$Musique$$, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$)
),
upsert_categories AS (
  INSERT INTO public.categories (slug, name, accent_color, tone, created_at, updated_at)
  SELECT slug, name, accent_color, tone, now(), now()
  FROM category_seed
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    accent_color = EXCLUDED.accent_color,
    tone = EXCLUDED.tone,
    updated_at = now()
  RETURNING id, slug
),
all_categories AS (
  SELECT id, slug FROM upsert_categories
  UNION
  SELECT id, slug
  FROM public.categories
  WHERE slug IN ($$histoire-essentielle$$, $$cinema-culture$$, $$grandes-figures$$, $$arts-litterature$$, $$science-accessible$$, $$inventions-technologie$$, $$quotidien-cache$$, $$mots-origines$$, $$monde-geographie$$, $$musique-culture$$)
),
fact_seed(slug, title, hook, content, source, category_slug, display_order, accent_color, tone) AS (
VALUES
  ($$la-premiere-guerre-mondiale-a-commence-en-1914$$, $$La Première Guerre mondiale a commencé en 1914.$$, $$La Première Guerre mondiale a commencé en 1914.$$, $$À l’origine, beaucoup pensaient que le conflit serait court. Il durera pourtant plus de quatre ans et bouleversera durablement l’Europe, ses frontières et sa manière de voir la guerre.$$, $$Encyclopaedia Britannica$$, $$histoire-essentielle$$, 1, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$la-revolution-francaise-a-commence-en-1789$$, $$La Révolution française a commencé en 1789.$$, $$La Révolution française a commencé en 1789.$$, $$Cette date marque le début d’un immense bouleversement politique en France. La prise de la Bastille, le 14 juillet 1789, est devenue l’un des symboles les plus connus de cette période.$$, $$Encyclopaedia Britannica$$, $$histoire-essentielle$$, 2, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$le-premier-pas-sur-la-lune-a-eu-lieu-en-1969$$, $$Le premier pas sur la Lune a eu lieu en 1969.$$, $$Le premier pas sur la Lune a eu lieu en 1969.$$, $$Neil Armstrong devient alors le premier humain à marcher sur la Lune. L’événement est suivi à la télévision par des centaines de millions de personnes, à une époque où cela paraît encore presque inimaginable.$$, $$NASA$$, $$histoire-essentielle$$, 3, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$le-mur-de-berlin-est-tombe-en-1989$$, $$Le mur de Berlin est tombé en 1989.$$, $$Le mur de Berlin est tombé en 1989.$$, $$Pendant près de trente ans, il a séparé Berlin en deux et symbolisé la division entre l’Est et l’Ouest. Sa chute est devenue l’une des images fortes de la fin de la guerre froide.$$, $$Encyclopaedia Britannica$$, $$histoire-essentielle$$, 4, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$christophe-colomb-atteint-lamerique-en-1492$$, $$Christophe Colomb atteint l’Amérique en 1492.$$, $$Christophe Colomb atteint l’Amérique en 1492.$$, $$Il ne pense pas avoir découvert un nouveau continent : il croit être arrivé près de l’Asie. C’est pourtant ce voyage qui marque, dans les manuels européens, le début des grandes explorations vers les Amériques.$$, $$Encyclopaedia Britannica$$, $$histoire-essentielle$$, 5, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$limprimerie-de-gutenberg-a-change-la-diffusion-du-savoir$$, $$L’imprimerie de Gutenberg a changé la diffusion du savoir.$$, $$L’imprimerie de Gutenberg a changé la diffusion du savoir.$$, $$Au XVe siècle, les livres deviennent plus faciles et moins chers à produire. Les idées circulent alors beaucoup plus vite, ce qui transforme profondément la religion, la science et la culture en Europe.$$, $$Bibliothèque nationale de France$$, $$histoire-essentielle$$, 6, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$la-guerre-froide-netait-pas-une-guerre-classique$$, $$La guerre froide n’était pas une guerre classique.$$, $$La guerre froide n’était pas une guerre classique.$$, $$Les États-Unis et l’URSS ne se sont jamais affrontés directement dans une grande bataille entre eux. Leur rivalité passait surtout par l’espionnage, la propagande, la course à l’espace et des conflits indirects.$$, $$Encyclopaedia Britannica$$, $$histoire-essentielle$$, 7, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$la-peste-noire-a-tue-une-immense-partie-de-leurope-au-xive-siecle$$, $$La peste noire a tué une immense partie de l’Europe au XIVe siècle.$$, $$La peste noire a tué une immense partie de l’Europe au XIVe siècle.$$, $$Entre 1347 et 1351, cette épidémie a bouleversé la société européenne. Elle a changé le rapport à la mort, au travail et même à la religion dans de nombreuses régions.$$, $$Encyclopaedia Britannica$$, $$histoire-essentielle$$, 8, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$la-declaration-des-droits-de-lhomme-date-de-1789$$, $$La Déclaration des droits de l’homme date de 1789.$$, $$La Déclaration des droits de l’homme date de 1789.$$, $$Elle affirme des principes devenus essentiels, comme la liberté et l’égalité devant la loi. Même si la réalité de l’époque restait très imparfaite, le texte est devenu une référence politique majeure.$$, $$Vie publique$$, $$histoire-essentielle$$, 9, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$le-11-novembre-marque-la-fin-des-combats-de-1918$$, $$Le 11 novembre marque la fin des combats de 1918.$$, $$Le 11 novembre marque la fin des combats de 1918.$$, $$L’armistice met fin aux combats de la Première Guerre mondiale, même si le traité de paix arrive plus tard. C’est pour cela que cette date reste associée au souvenir des soldats morts pendant la guerre.$$, $$Service public$$, $$histoire-essentielle$$, 10, $$#f97316$$, $$from-[#1c1917] via-[#7c2d12] to-[#fb923c]$$),
  ($$le-premier-film-de-lhistoire-date-de-1888$$, $$Le premier film de l’histoire date de 1888.$$, $$Le premier film de l’histoire date de 1888.$$, $$Il ne durait que quelques secondes et montrait simplement des personnes dans un jardin. À l’époque, voir des images bouger suffisait déjà à créer un vrai sentiment de magie.$$, $$Science Museum$$, $$cinema-culture$$, 11, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$charlie-chaplin-est-devenu-mondialement-celebre-sans-presque-parler$$, $$Charlie Chaplin est devenu mondialement célèbre sans presque parler.$$, $$Charlie Chaplin est devenu mondialement célèbre sans presque parler.$$, $$À l’époque du cinéma muet, ses gestes, son visage et sa silhouette suffisaient à faire comprendre ses histoires partout dans le monde. C’est ce qui a fait de lui une figure universelle du cinéma.$$, $$Encyclopaedia Britannica$$, $$cinema-culture$$, 12, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$hitchcock-est-surnomme-le-maitre-du-suspense$$, $$Hitchcock est surnommé le maître du suspense.$$, $$Hitchcock est surnommé le maître du suspense.$$, $$Il ne cherchait pas seulement à faire peur, mais à faire attendre le spectateur. Ses films comme Psychose ou Fenêtre sur cour ont marqué durablement la manière de créer de la tension au cinéma.$$, $$British Film Institute$$, $$cinema-culture$$, 13, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$pulp-fiction-est-raconte-dans-le-desordre-volontairement$$, $$Pulp Fiction est raconté dans le désordre volontairement.$$, $$Pulp Fiction est raconté dans le désordre volontairement.$$, $$Quentin Tarantino oblige le spectateur à reconstruire l’histoire lui-même. Cette structure a donné au film un style très reconnaissable et a marqué le cinéma des années 1990.$$, $$Festival de Cannes$$, $$cinema-culture$$, 14, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$star-wars-etait-un-pari-risque-au-depart$$, $$Star Wars était un pari risqué au départ.$$, $$Star Wars était un pari risqué au départ.$$, $$À sa sortie en 1977, son mélange de science-fiction, d’aventure et de mythologie paraissait étrange à beaucoup de studios. Le film deviendra pourtant l’une des sagas les plus célèbres de la culture populaire.$$, $$Lucasfilm$$, $$cinema-culture$$, 15, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$jurassic-park-a-change-les-effets-speciaux-modernes$$, $$Jurassic Park a changé les effets spéciaux modernes.$$, $$Jurassic Park a changé les effets spéciaux modernes.$$, $$Ses dinosaures mélangeaient animatroniques et images numériques avec un réalisme impressionnant pour l’époque. Après ce film, Hollywood comprend que les créatures numériques peuvent devenir crédibles à l’écran.$$, $$Industrial Light & Magic$$, $$cinema-culture$$, 16, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$le-parrain-a-failli-ne-pas-avoir-marlon-brando$$, $$Le Parrain a failli ne pas avoir Marlon Brando.$$, $$Le Parrain a failli ne pas avoir Marlon Brando.$$, $$Le studio doutait de lui et le jugeait difficile à gérer. Son interprétation deviendra pourtant l’une des plus célèbres de l’histoire du cinéma.$$, $$Paramount Pictures$$, $$cinema-culture$$, 17, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$titanic-a-longtemps-domine-le-box-office-mondial$$, $$Titanic a longtemps dominé le box-office mondial.$$, $$Titanic a longtemps dominé le box-office mondial.$$, $$Le film de James Cameron a marqué toute une génération avec son mélange de romance, de catastrophe et de reconstitution historique. Il a aussi remporté 11 Oscars, un record partagé avec quelques rares films.$$, $$Academy of Motion Picture Arts and Sciences$$, $$cinema-culture$$, 18, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$les-dents-de-la-mer-a-change-la-sortie-des-films-dete$$, $$Les dents de la mer a changé la sortie des films d’été.$$, $$Les dents de la mer a changé la sortie des films d’été.$$, $$Avant ce succès, l’été n’était pas forcément la grande saison des blockbusters. Le film a montré qu’un lancement massif pouvait transformer un film populaire en événement national.$$, $$Universal Pictures$$, $$cinema-culture$$, 19, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$les-films-pixar-commencent-souvent-avec-une-idee-tres-simple$$, $$Les films Pixar commencent souvent avec une idée très simple.$$, $$Les films Pixar commencent souvent avec une idée très simple.$$, $$Toy Story part d’une question que tout enfant peut comprendre : et si les jouets prenaient vie quand on quitte la pièce ? C’est cette simplicité qui rend l’univers immédiatement accessible.$$, $$Pixar$$, $$cinema-culture$$, 20, $$#ec4899$$, $$from-[#1f1020] via-[#831843] to-[#f472b6]$$),
  ($$einstein-nest-pas-seulement-connu-pour-avoir-ete-un-genie$$, $$Einstein n’est pas seulement connu pour avoir été un génie.$$, $$Einstein n’est pas seulement connu pour avoir été un génie.$$, $$Il a changé notre manière de penser le temps, l’espace et la gravité. Même sans comprendre les équations, retenir cela suffit déjà à mieux situer son importance culturelle.$$, $$Nobel Prize$$, $$grandes-figures$$, 21, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$napoleon-netait-probablement-pas-si-petit$$, $$Napoléon n’était probablement pas si petit.$$, $$Napoléon n’était probablement pas si petit.$$, $$Sa réputation vient en partie de caricatures anglaises et de confusions entre anciennes mesures. En réalité, sa taille était plutôt normale pour son époque.$$, $$Fondation Napoléon$$, $$grandes-figures$$, 22, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$marie-curie-a-recu-deux-prix-nobel$$, $$Marie Curie a reçu deux prix Nobel.$$, $$Marie Curie a reçu deux prix Nobel.$$, $$Elle est récompensée en physique puis en chimie, ce qui reste exceptionnel. Son nom est devenu associé à la radioactivité et à la place des femmes dans l’histoire des sciences.$$, $$Nobel Prize$$, $$grandes-figures$$, 23, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$martin-luther-king-est-devenu-le-visage-dun-combat-pour-les-droits-civiques$$, $$Martin Luther King est devenu le visage d’un combat pour les droits civiques.$$, $$Martin Luther King est devenu le visage d’un combat pour les droits civiques.$$, $$Son discours I Have a Dream est resté célèbre parce qu’il transforme une revendication politique en image simple et puissante : celle d’un avenir plus juste.$$, $$The King Center$$, $$grandes-figures$$, 24, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$cleopatre-etait-plus-proche-de-nous-que-des-pyramides$$, $$Cléopâtre était plus proche de nous que des pyramides.$$, $$Cléopâtre était plus proche de nous que des pyramides.$$, $$Les grandes pyramides d’Égypte existaient déjà depuis plus de deux mille ans quand elle a vécu. Cela donne une idée vertigineuse de l’ancienneté de la civilisation égyptienne.$$, $$Encyclopaedia Britannica$$, $$grandes-figures$$, 25, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$leonard-de-vinci-etait-autant-inventeur-quartiste$$, $$Léonard de Vinci était autant inventeur qu’artiste.$$, $$Léonard de Vinci était autant inventeur qu’artiste.$$, $$On connaît surtout la Joconde, mais ses carnets montrent aussi des machines, des études du corps et des idées très en avance pour son époque. Il symbolise l’esprit curieux de la Renaissance.$$, $$Musée du Louvre$$, $$grandes-figures$$, 26, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$rosa-parks-na-pas-seulement-refuse-de-ceder-sa-place$$, $$Rosa Parks n’a pas seulement refusé de céder sa place.$$, $$Rosa Parks n’a pas seulement refusé de céder sa place.$$, $$Son geste devient le point de départ d’un immense boycott des bus à Montgomery. Ce boycott a joué un rôle majeur dans le mouvement américain des droits civiques.$$, $$National Archives$$, $$grandes-figures$$, 27, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$gandhi-a-utilise-la-non-violence-comme-arme-politique$$, $$Gandhi a utilisé la non-violence comme arme politique.$$, $$Gandhi a utilisé la non-violence comme arme politique.$$, $$Son combat contre la domination britannique en Inde reposait sur la désobéissance civile et la résistance pacifique. C’est cette stratégie qui a inspiré de nombreux mouvements dans le monde.$$, $$Encyclopaedia Britannica$$, $$grandes-figures$$, 28, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$walt-disney-a-transforme-le-dessin-anime-en-empire-culturel$$, $$Walt Disney a transformé le dessin animé en empire culturel.$$, $$Walt Disney a transformé le dessin animé en empire culturel.$$, $$Mickey n’était pas seulement un personnage amusant : il est devenu le symbole d’un studio, puis d’un univers entier de films, de parcs et de produits culturels.$$, $$The Walt Disney Company$$, $$grandes-figures$$, 29, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$nelson-mandela-a-passe-27-ans-en-prison$$, $$Nelson Mandela a passé 27 ans en prison.$$, $$Nelson Mandela a passé 27 ans en prison.$$, $$Après sa libération, il devient président de l’Afrique du Sud et une figure mondiale de la réconciliation. Son histoire est devenue l’un des grands symboles politiques du XXe siècle.$$, $$Nelson Mandela Foundation$$, $$grandes-figures$$, 30, $$#8b5cf6$$, $$from-[#17132a] via-[#4c1d95] to-[#a78bfa]$$),
  ($$van-gogh-na-connu-la-celebrite-quapres-sa-mort$$, $$Van Gogh n’a connu la célébrité qu’après sa mort.$$, $$Van Gogh n’a connu la célébrité qu’après sa mort.$$, $$Aujourd’hui, ses tableaux font partie des œuvres les plus connues au monde. De son vivant, il a pourtant vécu pauvrement et a très peu vendu, ce qui rend son destin encore plus marquant.$$, $$Van Gogh Museum$$, $$arts-litterature$$, 31, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$picasso-savait-dessiner-de-maniere-tres-realiste$$, $$Picasso savait dessiner de manière très réaliste.$$, $$Picasso savait dessiner de manière très réaliste.$$, $$Avant ses œuvres cubistes, il maîtrisait déjà parfaitement le dessin classique. Son style étrange ou déformé était donc un choix artistique, pas un manque de technique.$$, $$Musée Picasso$$, $$arts-litterature$$, 32, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$la-joconde-est-celebre-aussi-parce-quelle-a-ete-volee$$, $$La Joconde est célèbre aussi parce qu’elle a été volée.$$, $$La Joconde est célèbre aussi parce qu’elle a été volée.$$, $$En 1911, le tableau disparaît du Louvre pendant plus de deux ans. L’affaire fait la une des journaux et contribue fortement à transformer la Joconde en icône mondiale.$$, $$Musée du Louvre$$, $$arts-litterature$$, 33, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$le-petit-prince-est-lun-des-livres-les-plus-traduits-au-monde$$, $$Le Petit Prince est l’un des livres les plus traduits au monde.$$, $$Le Petit Prince est l’un des livres les plus traduits au monde.$$, $$Sous son apparence de conte pour enfants, il parle de solitude, d’amitié et du regard adulte sur le monde. C’est cette double lecture qui le rend si universel.$$, $$Fondation Antoine de Saint-Exupéry$$, $$arts-litterature$$, 34, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$shakespeare-a-popularise-des-centaines-de-mots-et-dexpressions-anglaises$$, $$Shakespeare a popularisé des centaines de mots et d’expressions anglaises.$$, $$Shakespeare a popularisé des centaines de mots et d’expressions anglaises.$$, $$Ses pièces ont tellement marqué la langue que certaines formules sont encore utilisées aujourd’hui. Même sans avoir lu Shakespeare, on croise souvent son influence.$$, $$Shakespeare Birthplace Trust$$, $$arts-litterature$$, 35, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$les-impressionnistes-ont-dabord-ete-moques$$, $$Les impressionnistes ont d’abord été moqués.$$, $$Les impressionnistes ont d’abord été moqués.$$, $$Leur manière de peindre semblait inachevée à beaucoup de critiques. Aujourd’hui, Monet, Renoir ou Degas font partie des artistes les plus aimés du grand public.$$, $$Musée d’Orsay$$, $$arts-litterature$$, 36, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$guernica-de-picasso-repond-a-un-bombardement-reel$$, $$Guernica de Picasso répond à un bombardement réel.$$, $$Guernica de Picasso répond à un bombardement réel.$$, $$Le tableau dénonce la violence subie par la ville de Guernica pendant la guerre d’Espagne. Même sans montrer la scène de manière réaliste, il est devenu une image majeure contre la guerre.$$, $$Museo Reina Sofía$$, $$arts-litterature$$, 37, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$le-penseur-de-rodin-netait-pas-concu-comme-une-statue-isolee$$, $$Le Penseur de Rodin n’était pas conçu comme une statue isolée.$$, $$Le Penseur de Rodin n’était pas conçu comme une statue isolée.$$, $$La sculpture faisait d’abord partie d’un ensemble plus vaste inspiré de La Divine Comédie. Avec le temps, elle est devenue un symbole universel de la réflexion humaine.$$, $$Musée Rodin$$, $$arts-litterature$$, 38, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$frankenstein-a-ete-ecrit-par-mary-shelley-a-seulement-18-ans$$, $$Frankenstein a été écrit par Mary Shelley à seulement 18 ans.$$, $$Frankenstein a été écrit par Mary Shelley à seulement 18 ans.$$, $$Son roman raconte une créature fabriquée par un scientifique, mais pose surtout une question très moderne : que se passe-t-il quand l’humain crée quelque chose qu’il ne maîtrise plus ?$$, $$British Library$$, $$arts-litterature$$, 39, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$les-grottes-de-lascaux-ont-ete-decouvertes-par-hasard$$, $$Les grottes de Lascaux ont été découvertes par hasard.$$, $$Les grottes de Lascaux ont été découvertes par hasard.$$, $$En 1940, des adolescents tombent sur ces peintures préhistoriques en Dordogne. Elles montrent que les humains racontaient déjà le monde en images il y a des milliers d’années.$$, $$Ministère de la Culture$$, $$arts-litterature$$, 40, $$#06b6d4$$, $$from-[#071a20] via-[#164e63] to-[#67e8f9]$$),
  ($$ton-cerveau-reecrit-legerement-tes-souvenirs$$, $$Ton cerveau réécrit légèrement tes souvenirs.$$, $$Ton cerveau réécrit légèrement tes souvenirs.$$, $$Quand tu te rappelles quelque chose, ton cerveau ne relit pas un fichier intact : il reconstruit le souvenir. C’est pour cela qu’un souvenir peut changer avec le temps sans que tu t’en rendes compte.$$, $$Scientific American$$, $$science-accessible$$, 41, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$ton-cerveau-filtre-une-partie-de-ce-que-voient-tes-yeux$$, $$Ton cerveau filtre une partie de ce que voient tes yeux.$$, $$Ton cerveau filtre une partie de ce que voient tes yeux.$$, $$Il trie en permanence les informations pour éviter la surcharge. C’est pour cela qu’un détail pourtant visible peut parfois passer totalement inaperçu.$$, $$American Psychological Association$$, $$science-accessible$$, 42, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$le-miel-peut-rester-consommable-pendant-des-milliers-dannees$$, $$Le miel peut rester consommable pendant des milliers d’années.$$, $$Le miel peut rester consommable pendant des milliers d’années.$$, $$Il contient très peu d’eau et empêche la plupart des bactéries de se développer. C’est pour cela qu’on a retrouvé du miel ancien encore remarquablement bien conservé.$$, $$Smithsonian Magazine$$, $$science-accessible$$, 43, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$les-bananes-sont-legerement-radioactives$$, $$Les bananes sont légèrement radioactives.$$, $$Les bananes sont légèrement radioactives.$$, $$Elles contiennent naturellement du potassium, dont une petite partie émet de faibles radiations. La quantité est totalement inoffensive, mais l’idée reste assez surprenante pour un fruit aussi banal.$$, $$United States Environmental Protection Agency$$, $$science-accessible$$, 44, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$les-pieuvres-ont-trois-curs$$, $$Les pieuvres ont trois cœurs.$$, $$Les pieuvres ont trois cœurs.$$, $$Deux aident à envoyer le sang vers les branchies, et le troisième l’envoie dans le reste du corps. C’est l’un des détails qui rendent ces animaux si différents de nous.$$, $$Smithsonian Ocean$$, $$science-accessible$$, 45, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$une-journee-sur-venus-dure-plus-longtemps-quune-annee-sur-venus$$, $$Une journée sur Vénus dure plus longtemps qu’une année sur Vénus.$$, $$Une journée sur Vénus dure plus longtemps qu’une année sur Vénus.$$, $$La planète tourne très lentement sur elle-même. Elle met plus de temps à faire un tour complet sur elle-même qu’à faire le tour du Soleil.$$, $$NASA$$, $$science-accessible$$, 46, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$le-sommeil-aide-ton-cerveau-a-trier-la-journee$$, $$Le sommeil aide ton cerveau à trier la journée.$$, $$Le sommeil aide ton cerveau à trier la journée.$$, $$Dormir ne sert pas seulement à récupérer physiquement. Le cerveau consolide certains souvenirs et en écarte d’autres, un peu comme s’il rangeait ce qui mérite d’être gardé.$$, $$National Institute of Neurological Disorders and Stroke$$, $$science-accessible$$, 47, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$le-rire-nest-pas-seulement-une-reaction-a-lhumour$$, $$Le rire n’est pas seulement une réaction à l’humour.$$, $$Le rire n’est pas seulement une réaction à l’humour.$$, $$On rit aussi pour créer du lien, détendre une situation ou montrer qu’on est à l’aise avec les autres. C’est autant un comportement social qu’une réaction à une blague.$$, $$American Psychological Association$$, $$science-accessible$$, 48, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$le-poulpe-peut-changer-de-couleur-tres-rapidement$$, $$Le poulpe peut changer de couleur très rapidement.$$, $$Le poulpe peut changer de couleur très rapidement.$$, $$Sa peau contient de petites cellules capables de modifier son apparence. Cela lui sert à se camoufler, communiquer ou impressionner un adversaire.$$, $$Smithsonian Ocean$$, $$science-accessible$$, 49, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$la-peur-peut-rendre-certains-souvenirs-plus-forts$$, $$La peur peut rendre certains souvenirs plus forts.$$, $$La peur peut rendre certains souvenirs plus forts.$$, $$Quand une situation paraît dangereuse, le cerveau donne plus d’importance aux détails liés à l’événement. C’est une manière de mieux reconnaître un danger si quelque chose de similaire se reproduit.$$, $$Harvard Health Publishing$$, $$science-accessible$$, 50, $$#22c55e$$, $$from-[#061a12] via-[#14532d] to-[#86efac]$$),
  ($$le-premier-iphone-ne-permettait-pas-de-copier-coller$$, $$Le premier iPhone ne permettait pas de copier-coller.$$, $$Le premier iPhone ne permettait pas de copier-coller.$$, $$Présenté en 2007, il semblait pourtant révolutionnaire malgré l’absence de fonctions aujourd’hui évidentes. Cela montre à quel point une innovation peut commencer imparfaite et quand même changer les usages.$$, $$Apple$$, $$inventions-technologie$$, 51, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$internet-vient-dun-projet-militaire-et-universitaire$$, $$Internet vient d’un projet militaire et universitaire.$$, $$Internet vient d’un projet militaire et universitaire.$$, $$Avant de devenir un outil du quotidien, il servait à connecter des ordinateurs entre institutions. Ce réseau expérimental a fini par transformer presque tous les aspects de la vie moderne.$$, $$Internet Society$$, $$inventions-technologie$$, 52, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$le-premier-email-a-ete-envoye-dans-les-annees-1970$$, $$Le premier email a été envoyé dans les années 1970.$$, $$Le premier email a été envoyé dans les années 1970.$$, $$Le symbole @ a été choisi pour séparer le nom de l’utilisateur et celui de la machine. Aujourd’hui, ce petit signe est devenu l’un des symboles les plus courants du numérique.$$, $$Computer History Museum$$, $$inventions-technologie$$, 53, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$le-gps-depend-de-satellites-et-dhorloges-extremement-precises$$, $$Le GPS dépend de satellites et d’horloges extrêmement précises.$$, $$Le GPS dépend de satellites et d’horloges extrêmement précises.$$, $$Ton téléphone peut te localiser parce qu’il compare des signaux venus de plusieurs satellites. Sans cette précision du temps, la position serait rapidement fausse.$$, $$NASA$$, $$inventions-technologie$$, 54, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$la-photographie-a-dabord-demande-de-tres-longs-temps-de-pose$$, $$La photographie a d’abord demandé de très longs temps de pose.$$, $$La photographie a d’abord demandé de très longs temps de pose.$$, $$Les premières images nécessitaient plusieurs minutes, parfois davantage. C’est pour cela que les portraits anciens semblent souvent figés et très sérieux.$$, $$National Geographic$$, $$inventions-technologie$$, 55, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$le-code-barres-a-ete-inspire-par-le-sable$$, $$Le code-barres a été inspiré par le sable.$$, $$Le code-barres a été inspiré par le sable.$$, $$L’un de ses inventeurs aurait tracé des lignes dans le sable en réfléchissant au problème. Ces lignes deviendront l’idée de base d’un système utilisé ensuite dans presque tous les magasins.$$, $$Smithsonian Magazine$$, $$inventions-technologie$$, 56, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$la-machine-a-ecrire-a-influence-nos-claviers-modernes$$, $$La machine à écrire a influencé nos claviers modernes.$$, $$La machine à écrire a influencé nos claviers modernes.$$, $$La disposition QWERTY vient d’une époque mécanique où les touches pouvaient se bloquer. Même si les ordinateurs n’ont plus ce problème, l’habitude est restée.$$, $$Computer History Museum$$, $$inventions-technologie$$, 57, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$les-premiers-ordinateurs-occupaient-des-pieces-entieres$$, $$Les premiers ordinateurs occupaient des pièces entières.$$, $$Les premiers ordinateurs occupaient des pièces entières.$$, $$Ils étaient beaucoup moins puissants que nos téléphones actuels, mais demandaient énormément d’espace et d’énergie. Cela rend l’évolution de l’informatique encore plus spectaculaire.$$, $$Computer History Museum$$, $$inventions-technologie$$, 58, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$la-television-couleur-a-mis-du-temps-a-devenir-normale$$, $$La télévision couleur a mis du temps à devenir normale.$$, $$La télévision couleur a mis du temps à devenir normale.$$, $$Pendant des années, beaucoup de foyers regardaient encore la télévision en noir et blanc. Ce qui nous paraît évident aujourd’hui a longtemps été un luxe ou une nouveauté.$$, $$INA$$, $$inventions-technologie$$, 59, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$le-velcro-sinspire-dune-plante-accrochee-aux-vetements$$, $$Le Velcro s’inspire d’une plante accrochée aux vêtements.$$, $$Le Velcro s’inspire d’une plante accrochée aux vêtements.$$, $$Son inventeur a observé des petits crochets naturels sur des bardanes après une promenade. Cette observation simple a donné naissance à un système de fermeture utilisé partout.$$, $$The Velcro Companies$$, $$inventions-technologie$$, 60, $$#3b82f6$$, $$from-[#071426] via-[#1d4ed8] to-[#93c5fd]$$),
  ($$les-cartes-du-monde-deforment-la-taille-reelle-des-pays$$, $$Les cartes du monde déforment la taille réelle des pays.$$, $$Les cartes du monde déforment la taille réelle des pays.$$, $$Sur certaines cartes, le Groenland paraît presque aussi grand que l’Afrique. En réalité, l’Afrique est environ 14 fois plus grande, car représenter une sphère à plat crée forcément des déformations.$$, $$National Geographic$$, $$quotidien-cache$$, 61, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$le-ketchup-a-deja-ete-vendu-comme-medicament$$, $$Le ketchup a déjà été vendu comme médicament.$$, $$Le ketchup a déjà été vendu comme médicament.$$, $$Au XIXe siècle, certains le présentaient comme bon pour la digestion. Difficile à imaginer aujourd’hui, quand on le voit surtout comme une sauce de fast-food.$$, $$Smithsonian Magazine$$, $$quotidien-cache$$, 62, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$les-carottes-nont-pas-toujours-ete-orange$$, $$Les carottes n’ont pas toujours été orange.$$, $$Les carottes n’ont pas toujours été orange.$$, $$Des variétés violettes, blanches ou jaunes existaient déjà depuis longtemps. La carotte orange s’est surtout imposée en Europe au fil des sélections agricoles.$$, $$World Carrot Museum$$, $$quotidien-cache$$, 63, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$le-cafe-a-longtemps-ete-suspect-dans-certains-pays$$, $$Le café a longtemps été suspect dans certains pays.$$, $$Le café a longtemps été suspect dans certains pays.$$, $$Comme il rendait les gens plus éveillés et favorisait les discussions dans les cafés, certains dirigeants s’en méfiaient. Une simple boisson pouvait devenir un lieu de débat politique.$$, $$Encyclopaedia Britannica$$, $$quotidien-cache$$, 64, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$les-jeans-etaient-dabord-des-vetements-de-travail$$, $$Les jeans étaient d’abord des vêtements de travail.$$, $$Les jeans étaient d’abord des vêtements de travail.$$, $$Leur tissu solide convenait aux ouvriers, mineurs et chercheurs d’or. Aujourd’hui, ils sont devenus l’un des vêtements les plus universels au monde.$$, $$Levi Strauss & Co.$$, $$quotidien-cache$$, 65, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$les-talons-hauts-etaient-dabord-portes-par-des-hommes$$, $$Les talons hauts étaient d’abord portés par des hommes.$$, $$Les talons hauts étaient d’abord portés par des hommes.$$, $$Ils servaient notamment aux cavaliers pour mieux tenir les étriers. Avec le temps, ils sont devenus un symbole de mode associé surtout aux femmes.$$, $$Victoria and Albert Museum$$, $$quotidien-cache$$, 66, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$la-fourchette-a-mis-longtemps-a-simposer-en-europe$$, $$La fourchette a mis longtemps à s’imposer en Europe.$$, $$La fourchette a mis longtemps à s’imposer en Europe.$$, $$Pendant des siècles, manger avec les doigts ou avec un couteau était courant. La fourchette a d’abord semblé étrange avant de devenir un objet de table évident.$$, $$Victoria and Albert Museum$$, $$quotidien-cache$$, 67, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$les-anniversaires-avec-bougies-viennent-de-traditions-tres-anciennes$$, $$Les anniversaires avec bougies viennent de traditions très anciennes.$$, $$Les anniversaires avec bougies viennent de traditions très anciennes.$$, $$L’idée d’associer gâteau, lumière et souhait s’est construite progressivement. Aujourd’hui, souffler des bougies paraît naturel, mais c’est un rituel culturel hérité de plusieurs influences.$$, $$History$$, $$quotidien-cache$$, 68, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$le-chewing-gum-moderne-vient-dune-matiere-naturelle-machee-depuis-longtemps$$, $$Le chewing-gum moderne vient d’une matière naturelle mâchée depuis longtemps.$$, $$Le chewing-gum moderne vient d’une matière naturelle mâchée depuis longtemps.$$, $$Bien avant les marques industrielles, des peuples mâchaient déjà des résines ou des gommes végétales. L’envie de mâcher quelque chose ne date donc pas des supermarchés.$$, $$Smithsonian Magazine$$, $$quotidien-cache$$, 69, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$les-supermarches-sont-penses-pour-guider-tes-choix$$, $$Les supermarchés sont pensés pour guider tes choix.$$, $$Les supermarchés sont pensés pour guider tes choix.$$, $$L’emplacement des produits, les promotions et les rayons ne sont pas laissés au hasard. Tout est conçu pour rendre certains achats plus visibles ou plus tentants.$$, $$NielsenIQ$$, $$quotidien-cache$$, 70, $$#f59e0b$$, $$from-[#1c1608] via-[#92400e] to-[#fbbf24]$$),
  ($$le-mot-robot-vient-dun-mot-lie-au-travail-force$$, $$Le mot robot vient d’un mot lié au travail forcé.$$, $$Le mot robot vient d’un mot lié au travail forcé.$$, $$Il apparaît dans une pièce tchèque des années 1920. À l’origine, les robots étaient imaginés comme des travailleurs artificiels créés pour servir les humains.$$, $$Science Museum$$, $$mots-origines$$, 71, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-salaire-est-lie-au-sel$$, $$Le mot salaire est lié au sel.$$, $$Le mot salaire est lié au sel.$$, $$Dans l’Antiquité romaine, le sel avait une grande valeur et était lié à certaines formes de paiement ou d’allocation. C’est de cette racine que vient le mot latin salarium.$$, $$Dictionnaire de l’Académie française$$, $$mots-origines$$, 72, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-deadline-avait-autrefois-un-sens-beaucoup-plus-sombre$$, $$Le mot deadline avait autrefois un sens beaucoup plus sombre.$$, $$Le mot deadline avait autrefois un sens beaucoup plus sombre.$$, $$Pendant la guerre de Sécession, il désignait une ligne à ne pas franchir dans certains camps de prisonniers. Le mot a ensuite évolué pour désigner une limite de temps.$$, $$Merriam-Webster$$, $$mots-origines$$, 73, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-boycott-vient-du-nom-dun-homme$$, $$Le mot boycott vient du nom d’un homme.$$, $$Le mot boycott vient du nom d’un homme.$$, $$Charles Boycott était un propriétaire dont les habitants ont refusé les services et les échanges. Son nom est devenu un mot utilisé dans plusieurs langues pour désigner ce type de refus collectif.$$, $$Encyclopaedia Britannica$$, $$mots-origines$$, 74, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-sandwich-vient-dun-comte-anglais$$, $$Le mot sandwich vient d’un comte anglais.$$, $$Le mot sandwich vient d’un comte anglais.$$, $$Le comte de Sandwich aurait popularisé l’idée de manger de la viande entre deux tranches de pain pour ne pas interrompre ses activités. Son nom est resté attaché au repas lui-même.$$, $$Oxford English Dictionary$$, $$mots-origines$$, 75, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-musee-vient-des-muses-de-la-mythologie-grecque$$, $$Le mot musée vient des Muses de la mythologie grecque.$$, $$Le mot musée vient des Muses de la mythologie grecque.$$, $$Les Muses étaient associées aux arts, à la poésie et au savoir. Le mot a fini par désigner un lieu où l’on conserve et transmet la culture.$$, $$CNRTL$$, $$mots-origines$$, 76, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-assassin-vient-dune-histoire-medievale-complexe$$, $$Le mot assassin vient d’une histoire médiévale complexe.$$, $$Le mot assassin vient d’une histoire médiévale complexe.$$, $$Il est lié à une secte orientale connue en Europe par des récits souvent exagérés. Avec le temps, le mot a fini par désigner une personne qui tue volontairement quelqu’un.$$, $$CNRTL$$, $$mots-origines$$, 77, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-mascara-vient-dun-mot-lie-au-masque$$, $$Le mot mascara vient d’un mot lié au masque.$$, $$Le mot mascara vient d’un mot lié au masque.$$, $$Son origine rappelle l’idée de couvrir ou transformer le regard. C’est assez logique pour un produit qui modifie immédiatement l’apparence des yeux.$$, $$CNRTL$$, $$mots-origines$$, 78, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-algorithme-vient-du-nom-dun-savant$$, $$Le mot algorithme vient du nom d’un savant.$$, $$Le mot algorithme vient du nom d’un savant.$$, $$Il vient d’Al-Khwârizmî, un mathématicien persan du IXe siècle. Aujourd’hui, son nom se cache derrière un mot central de l’informatique moderne.$$, $$Encyclopaedia Britannica$$, $$mots-origines$$, 79, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$le-mot-echec-et-mat-signifie-que-le-roi-est-vaincu$$, $$Le mot échec et mat signifie que le roi est vaincu.$$, $$Le mot échec et mat signifie que le roi est vaincu.$$, $$L’expression vient du monde persan et arabe des échecs. Elle rappelle que ce jeu a voyagé à travers plusieurs cultures avant de devenir un classique mondial.$$, $$Encyclopaedia Britannica$$, $$mots-origines$$, 80, $$#14b8a6$$, $$from-[#06221f] via-[#0f766e] to-[#5eead4]$$),
  ($$lafrique-est-beaucoup-plus-grande-quelle-ne-parait-sur-certaines-cartes$$, $$L’Afrique est beaucoup plus grande qu’elle ne paraît sur certaines cartes.$$, $$L’Afrique est beaucoup plus grande qu’elle ne paraît sur certaines cartes.$$, $$Beaucoup de cartes agrandissent visuellement les régions proches des pôles. En réalité, le continent africain peut contenir les États-Unis, la Chine, l’Inde et une grande partie de l’Europe réunis.$$, $$National Geographic$$, $$monde-geographie$$, 81, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$istanbul-est-a-cheval-sur-deux-continents$$, $$Istanbul est à cheval sur deux continents.$$, $$Istanbul est à cheval sur deux continents.$$, $$Une partie de la ville se trouve en Europe et l’autre en Asie. Cette position explique pourquoi Istanbul a longtemps été un carrefour majeur entre plusieurs mondes.$$, $$Encyclopaedia Britannica$$, $$monde-geographie$$, 82, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$le-japon-compte-des-milliers-diles$$, $$Le Japon compte des milliers d’îles.$$, $$Le Japon compte des milliers d’îles.$$, $$On pense souvent aux grandes îles principales, mais l’archipel est composé d’un très grand nombre d’îles. Cela explique en partie son rapport particulier à la mer et aux séismes.$$, $$National Geographic$$, $$monde-geographie$$, 83, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$le-nil-a-longtemps-ete-considere-comme-le-plus-long-fleuve-du-monde$$, $$Le Nil a longtemps été considéré comme le plus long fleuve du monde.$$, $$Le Nil a longtemps été considéré comme le plus long fleuve du monde.$$, $$Il traverse plusieurs pays africains et a permis le développement de l’Égypte antique. Sans ses crues et ses terres fertiles, cette civilisation n’aurait pas eu la même histoire.$$, $$Encyclopaedia Britannica$$, $$monde-geographie$$, 84, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$le-sahara-nest-pas-seulement-du-sable$$, $$Le Sahara n’est pas seulement du sable.$$, $$Le Sahara n’est pas seulement du sable.$$, $$On imagine souvent des dunes à perte de vue, mais le désert contient aussi des plateaux rocheux, des montagnes et des zones très variées. Le cliché du désert uniforme est donc trompeur.$$, $$National Geographic$$, $$monde-geographie$$, 85, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$lantarctique-est-un-desert$$, $$L’Antarctique est un désert.$$, $$L’Antarctique est un désert.$$, $$Même couvert de glace, il reçoit très peu de précipitations. Un désert n’est donc pas forcément chaud : c’est surtout un endroit où il tombe très peu d’eau.$$, $$National Geographic$$, $$monde-geographie$$, 86, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$la-mer-morte-est-si-salee-quon-y-flotte-facilement$$, $$La mer Morte est si salée qu’on y flotte facilement.$$, $$La mer Morte est si salée qu’on y flotte facilement.$$, $$Sa forte concentration en sel rend l’eau beaucoup plus dense que celle des mers classiques. C’est ce qui donne cette sensation étrange de flotter presque sans effort.$$, $$Encyclopaedia Britannica$$, $$monde-geographie$$, 87, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$le-canada-possede-plus-de-lacs-que-nimporte-quel-autre-pays$$, $$Le Canada possède plus de lacs que n’importe quel autre pays.$$, $$Le Canada possède plus de lacs que n’importe quel autre pays.$$, $$Une grande partie de son territoire a été façonnée par les glaciers. Résultat : le pays compte une quantité immense de lacs, parfois dans des régions presque inhabitées.$$, $$The Canadian Encyclopedia$$, $$monde-geographie$$, 88, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$le-mont-everest-continue-de-grandir-tres-lentement$$, $$Le mont Everest continue de grandir très lentement.$$, $$Le mont Everest continue de grandir très lentement.$$, $$La collision entre les plaques tectoniques indienne et eurasienne pousse encore l’Himalaya vers le haut. À l’échelle humaine, c’est presque imperceptible, mais à l’échelle géologique, c’est énorme.$$, $$National Geographic$$, $$monde-geographie$$, 89, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$venise-est-construite-sur-une-lagune$$, $$Venise est construite sur une lagune.$$, $$Venise est construite sur une lagune.$$, $$La ville repose sur des îlots et des structures en bois enfoncées dans le sol humide. C’est ce qui rend son architecture aussi fascinante, mais aussi vulnérable à l’eau.$$, $$UNESCO$$, $$monde-geographie$$, 90, $$#84cc16$$, $$from-[#101a08] via-[#3f6212] to-[#bef264]$$),
  ($$mozart-composait-deja-enfant$$, $$Mozart composait déjà enfant.$$, $$Mozart composait déjà enfant.$$, $$Il se produit très jeune devant les cours européennes. Son nom est devenu l’exemple classique du génie musical précoce, même pour ceux qui ne connaissent pas ses œuvres en détail.$$, $$Encyclopaedia Britannica$$, $$musique-culture$$, 91, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$beethoven-a-compose-certaines-uvres-alors-quil-devenait-sourd$$, $$Beethoven a composé certaines œuvres alors qu’il devenait sourd.$$, $$Beethoven a composé certaines œuvres alors qu’il devenait sourd.$$, $$Sa perte d’audition rend son parcours encore plus impressionnant. Imaginer un compositeur créer de la musique sans pouvoir l’entendre normalement donne une force particulière à son histoire.$$, $$Beethoven-Haus Bonn$$, $$musique-culture$$, 92, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$les-beatles-ont-transforme-la-musique-populaire$$, $$Les Beatles ont transformé la musique populaire.$$, $$Les Beatles ont transformé la musique populaire.$$, $$Ils n’ont pas seulement enchaîné les tubes : ils ont aussi changé la manière d’enregistrer, d’écrire des albums et de penser l’image d’un groupe. Leur influence dépasse largement les années 1960.$$, $$The Beatles$$, $$musique-culture$$, 93, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$le-jazz-nait-dun-melange-de-cultures$$, $$Le jazz naît d’un mélange de cultures.$$, $$Le jazz naît d’un mélange de cultures.$$, $$Il s’est développé notamment à La Nouvelle-Orléans, avec des influences africaines, européennes et américaines. C’est une musique construite sur le rythme, l’improvisation et le dialogue entre musiciens.$$, $$Smithsonian Music$$, $$musique-culture$$, 94, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$le-hip-hop-est-ne-dans-le-bronx-dans-les-annees-1970$$, $$Le hip-hop est né dans le Bronx dans les années 1970.$$, $$Le hip-hop est né dans le Bronx dans les années 1970.$$, $$Au départ, il rassemble musique, danse, graffiti et art de la parole. Ce qui était une culture de quartier est devenu l’un des mouvements culturels les plus influents du monde.$$, $$Smithsonian Music$$, $$musique-culture$$, 95, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$bob-marley-a-rendu-le-reggae-mondialement-celebre$$, $$Bob Marley a rendu le reggae mondialement célèbre.$$, $$Bob Marley a rendu le reggae mondialement célèbre.$$, $$Sa musique a porté le reggae bien au-delà de la Jamaïque. Ses chansons restent associées à la paix, à la résistance et à une identité culturelle très forte.$$, $$Rock & Roll Hall of Fame$$, $$musique-culture$$, 96, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$michael-jackson-a-transforme-le-clip-musical-en-evenement$$, $$Michael Jackson a transformé le clip musical en événement.$$, $$Michael Jackson a transformé le clip musical en événement.$$, $$Avec Thriller, le clip devient presque un court-métrage. Après cela, l’image devient aussi importante que la chanson dans la culture pop mondiale.$$, $$Rock & Roll Hall of Fame$$, $$musique-culture$$, 97, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$edith-piaf-reste-lune-des-voix-les-plus-celebres-de-la-chanson-francaise$$, $$Édith Piaf reste l’une des voix les plus célèbres de la chanson française.$$, $$Édith Piaf reste l’une des voix les plus célèbres de la chanson française.$$, $$Sa manière de chanter donnait l’impression de raconter une vie entière en quelques minutes. C’est pour cela que des titres comme La Vie en rose restent connus bien au-delà de la France.$$, $$INA$$, $$musique-culture$$, 98, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$le-rocknroll-a-dabord-choque-une-partie-des-adultes$$, $$Le rock’n’roll a d’abord choqué une partie des adultes.$$, $$Le rock’n’roll a d’abord choqué une partie des adultes.$$, $$Ses rythmes, ses danses et son énergie semblaient provocants dans les années 1950. Ce qui paraît classique aujourd’hui était alors perçu comme une rupture générationnelle.$$, $$Rock & Roll Hall of Fame$$, $$musique-culture$$, 99, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$),
  ($$la-marseillaise-etait-dabord-un-chant-de-guerre$$, $$La Marseillaise était d’abord un chant de guerre.$$, $$La Marseillaise était d’abord un chant de guerre.$$, $$Écrite en 1792, elle accompagne un contexte révolutionnaire et militaire. Elle deviendra ensuite l’hymne national français, ce qui explique son ton très intense.$$, $$Élysée$$, $$musique-culture$$, 100, $$#ef4444$$, $$from-[#220b0b] via-[#991b1b] to-[#fca5a5]$$)
),
inserted_facts AS (
  INSERT INTO public.facts (
    slug,
    title,
    hook,
    content,
    source,
    category_id,
    display_order,
    status,
    published_at,
    accent_color,
    tone,
    created_at,
    updated_at
  )
  SELECT
    fs.slug,
    fs.title,
    fs.hook,
    fs.content,
    fs.source,
    c.id,
    fs.display_order,
    'published',
    now(),
    fs.accent_color,
    fs.tone,
    now(),
    now()
  FROM fact_seed fs
  JOIN all_categories c ON c.slug = fs.category_slug
  WHERE NOT EXISTS (
    SELECT 1
    FROM public.facts existing
    WHERE existing.slug = fs.slug
  )
  RETURNING id
)
SELECT
  (SELECT count(*) FROM category_seed) AS categories_preparees,
  (SELECT count(*) FROM inserted_facts) AS faits_inseres;

COMMIT;
