-- Grumm feed V2: lightweight server-side scoring with session memory.
-- The RPC limits candidates before scoring, so the feed request does not rank
-- the whole facts table as content volume grows.

create table if not exists public.analytics_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  anonymous_id text,
  platform text not null check (platform in ('web', 'ios')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  facts_viewed integer not null default 0 check (facts_viewed >= 0),
  created_at timestamptz not null default now(),
  constraint analytics_sessions_identity_check check (
    user_id is not null or anonymous_id is not null
  )
);

create table if not exists public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.analytics_sessions(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  anonymous_id text,
  event_name text not null,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  platform text not null check (platform in ('web', 'ios')),
  created_at timestamptz not null default now(),
  constraint analytics_events_identity_check check (
    user_id is not null or anonymous_id is not null
  )
);

create table if not exists public.fact_read_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.analytics_sessions(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  anonymous_id text,
  fact_id uuid not null references public.facts(id) on delete cascade,
  platform text not null check (platform in ('web', 'ios')),
  started_at timestamptz not null,
  ended_at timestamptz,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  constraint fact_read_events_identity_check check (
    user_id is not null or anonymous_id is not null
  )
);

create table if not exists public.fact_engagement_stats (
  fact_id uuid primary key references public.facts(id) on delete cascade,
  views_count integer not null default 0 check (views_count >= 0),
  unique_viewers_count integer not null default 0 check (unique_viewers_count >= 0),
  likes_count integer not null default 0 check (likes_count >= 0),
  saves_count integer not null default 0 check (saves_count >= 0),
  shares_count integer not null default 0 check (shares_count >= 0),
  quiz_success_count integer not null default 0 check (quiz_success_count >= 0),
  quiz_attempt_count integer not null default 0 check (quiz_attempt_count >= 0),
  updated_at timestamptz not null default now()
);

comment on table public.fact_engagement_stats is
  'Aggregated per-fact counters used by get_personalized_feed. Kept outside the feed request to avoid expensive runtime counts.';

create table if not exists public.feed_sessions (
  id uuid primary key,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

comment on table public.feed_sessions is
  'Lightweight server-side memory for a feed browsing session, including anonymous sessions generated by the client.';

create table if not exists public.feed_session_items (
  session_id uuid not null references public.feed_sessions(id) on delete cascade,
  fact_id uuid not null references public.facts(id) on delete cascade,
  served_at timestamptz not null default now(),
  primary key (session_id, fact_id)
);

comment on table public.feed_session_items is
  'Facts already served during a feed session. Used as a temporary penalty to reduce duplicates in infinite scroll.';

create index if not exists facts_status_published_at_idx
  on public.facts (status, published_at desc);

create index if not exists facts_category_id_idx
  on public.facts (category_id);

create index if not exists facts_difficulty_level_idx
  on public.facts (difficulty_level);

create index if not exists facts_event_month_day_idx
  on public.facts (event_month, event_day)
  where status = 'published';

create index if not exists user_fact_views_user_fact_viewed_idx
  on public.user_fact_views (user_id, fact_id, first_viewed_at desc);

create index if not exists likes_user_fact_idx
  on public.likes (user_id, fact_id);

create index if not exists saves_user_fact_idx
  on public.saves (user_id, fact_id);

create index if not exists feed_sessions_user_seen_idx
  on public.feed_sessions (user_id, last_seen_at desc);

create index if not exists feed_session_items_session_fact_idx
  on public.feed_session_items (session_id, fact_id);

create index if not exists feed_session_items_served_idx
  on public.feed_session_items (served_at desc);

create index if not exists fact_engagement_stats_fact_id_idx
  on public.fact_engagement_stats (fact_id);

create index if not exists analytics_sessions_started_at_idx
  on public.analytics_sessions (started_at desc);

create index if not exists analytics_sessions_user_id_idx
  on public.analytics_sessions (user_id);

create index if not exists analytics_sessions_anonymous_id_idx
  on public.analytics_sessions (anonymous_id);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

create index if not exists analytics_events_entity_idx
  on public.analytics_events (entity_type, entity_id);

create index if not exists fact_read_events_fact_id_idx
  on public.fact_read_events (fact_id);

create index if not exists fact_read_events_session_id_idx
  on public.fact_read_events (session_id);

create index if not exists fact_read_events_user_id_idx
  on public.fact_read_events (user_id);

create index if not exists fact_read_events_created_at_idx
  on public.fact_read_events (created_at desc);

insert into public.fact_engagement_stats (
  fact_id,
  views_count,
  unique_viewers_count,
  likes_count,
  saves_count,
  shares_count,
  updated_at
)
select
  facts.id,
  coalesce(read_events.views_count, 0),
  coalesce(unique_views.unique_viewers_count, 0),
  coalesce(likes.likes_count, 0),
  coalesce(saves.saves_count, 0),
  coalesce(shares.shares_count, 0),
  now()
from public.facts
left join (
  select fact_id, count(*)::integer as views_count
  from public.fact_read_events
  group by fact_id
) read_events on read_events.fact_id = facts.id
left join (
  select fact_id, count(*)::integer as unique_viewers_count
  from public.user_fact_views
  group by fact_id
) unique_views on unique_views.fact_id = facts.id
left join (
  select fact_id, count(*)::integer as likes_count
  from public.likes
  group by fact_id
) likes on likes.fact_id = facts.id
left join (
  select fact_id, count(*)::integer as saves_count
  from public.saves
  group by fact_id
) saves on saves.fact_id = facts.id
left join (
  select entity_id as fact_id, count(*)::integer as shares_count
  from public.analytics_events
  where entity_type = 'fact'
    and event_name in ('fact_shared', 'fact_share')
    and entity_id is not null
  group by entity_id
) shares on shares.fact_id = facts.id
on conflict (fact_id) do update set
  views_count = excluded.views_count,
  unique_viewers_count = excluded.unique_viewers_count,
  likes_count = excluded.likes_count,
  saves_count = excluded.saves_count,
  shares_count = excluded.shares_count,
  updated_at = now();

create or replace function public.bump_fact_engagement_stat(
  p_fact_id uuid,
  p_metric text,
  p_delta integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.fact_engagement_stats (fact_id)
  values (p_fact_id)
  on conflict (fact_id) do nothing;

  update public.fact_engagement_stats
  set
    views_count = greatest(
      0,
      views_count + case when p_metric = 'views_count' then p_delta else 0 end
    ),
    unique_viewers_count = greatest(
      0,
      unique_viewers_count + case when p_metric = 'unique_viewers_count' then p_delta else 0 end
    ),
    likes_count = greatest(
      0,
      likes_count + case when p_metric = 'likes_count' then p_delta else 0 end
    ),
    saves_count = greatest(
      0,
      saves_count + case when p_metric = 'saves_count' then p_delta else 0 end
    ),
    shares_count = greatest(
      0,
      shares_count + case when p_metric = 'shares_count' then p_delta else 0 end
    ),
    quiz_success_count = greatest(
      0,
      quiz_success_count + case when p_metric = 'quiz_success_count' then p_delta else 0 end
    ),
    quiz_attempt_count = greatest(
      0,
      quiz_attempt_count + case when p_metric = 'quiz_attempt_count' then p_delta else 0 end
    ),
    updated_at = now()
  where fact_id = p_fact_id;
end;
$$;

create or replace function public.track_fact_read_engagement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.bump_fact_engagement_stat(new.fact_id, 'views_count', 1);
  return new;
end;
$$;

drop trigger if exists track_fact_read_engagement on public.fact_read_events;
create trigger track_fact_read_engagement
after insert on public.fact_read_events
for each row execute function public.track_fact_read_engagement();

create or replace function public.track_unique_fact_view_engagement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.bump_fact_engagement_stat(new.fact_id, 'unique_viewers_count', 1);
    return new;
  end if;

  perform public.bump_fact_engagement_stat(old.fact_id, 'unique_viewers_count', -1);
  return old;
end;
$$;

drop trigger if exists track_unique_fact_view_engagement_insert on public.user_fact_views;
create trigger track_unique_fact_view_engagement_insert
after insert on public.user_fact_views
for each row execute function public.track_unique_fact_view_engagement();

drop trigger if exists track_unique_fact_view_engagement_delete on public.user_fact_views;
create trigger track_unique_fact_view_engagement_delete
after delete on public.user_fact_views
for each row execute function public.track_unique_fact_view_engagement();

create or replace function public.track_like_engagement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.bump_fact_engagement_stat(new.fact_id, 'likes_count', 1);
    return new;
  end if;

  perform public.bump_fact_engagement_stat(old.fact_id, 'likes_count', -1);
  return old;
end;
$$;

drop trigger if exists track_like_engagement_insert on public.likes;
create trigger track_like_engagement_insert
after insert on public.likes
for each row execute function public.track_like_engagement();

drop trigger if exists track_like_engagement_delete on public.likes;
create trigger track_like_engagement_delete
after delete on public.likes
for each row execute function public.track_like_engagement();

create or replace function public.track_save_engagement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.bump_fact_engagement_stat(new.fact_id, 'saves_count', 1);
    return new;
  end if;

  perform public.bump_fact_engagement_stat(old.fact_id, 'saves_count', -1);
  return old;
end;
$$;

drop trigger if exists track_save_engagement_insert on public.saves;
create trigger track_save_engagement_insert
after insert on public.saves
for each row execute function public.track_save_engagement();

drop trigger if exists track_save_engagement_delete on public.saves;
create trigger track_save_engagement_delete
after delete on public.saves
for each row execute function public.track_save_engagement();

create or replace function public.track_share_engagement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.entity_type = 'fact'
    and new.entity_id is not null
    and new.event_name in ('fact_shared', 'fact_share') then
    perform public.bump_fact_engagement_stat(new.entity_id, 'shares_count', 1);
  end if;

  return new;
end;
$$;

drop trigger if exists track_share_engagement_insert on public.analytics_events;
create trigger track_share_engagement_insert
after insert on public.analytics_events
for each row execute function public.track_share_engagement();

alter table public.analytics_sessions enable row level security;
alter table public.analytics_events enable row level security;
alter table public.fact_read_events enable row level security;
alter table public.fact_engagement_stats enable row level security;
alter table public.feed_sessions enable row level security;
alter table public.feed_session_items enable row level security;

drop policy if exists "Clients can create analytics sessions" on public.analytics_sessions;
create policy "Clients can create analytics sessions"
on public.analytics_sessions for insert
to anon, authenticated
with check (
  platform in ('web', 'ios')
  and (
    (auth.uid() is not null and user_id = auth.uid())
    or (user_id is null and anonymous_id is not null)
  )
);

drop policy if exists "Clients can update analytics sessions" on public.analytics_sessions;
create policy "Clients can update analytics sessions"
on public.analytics_sessions for update
to anon, authenticated
using (
  (auth.uid() is not null and user_id = auth.uid())
  or (user_id is null and anonymous_id is not null)
)
with check (
  (auth.uid() is not null and user_id = auth.uid())
  or (user_id is null and anonymous_id is not null)
);

drop policy if exists "Admins can read analytics sessions" on public.analytics_sessions;
create policy "Admins can read analytics sessions"
on public.analytics_sessions for select
to authenticated
using (public.is_admin());

drop policy if exists "Clients can create analytics events" on public.analytics_events;
create policy "Clients can create analytics events"
on public.analytics_events for insert
to anon, authenticated
with check (
  platform in ('web', 'ios')
  and jsonb_typeof(metadata) = 'object'
  and (
    (auth.uid() is not null and user_id = auth.uid())
    or (user_id is null and anonymous_id is not null)
  )
);

drop policy if exists "Admins can read analytics events" on public.analytics_events;
create policy "Admins can read analytics events"
on public.analytics_events for select
to authenticated
using (public.is_admin());

drop policy if exists "Clients can create fact read events" on public.fact_read_events;
create policy "Clients can create fact read events"
on public.fact_read_events for insert
to anon, authenticated
with check (
  platform in ('web', 'ios')
  and (
    (auth.uid() is not null and user_id = auth.uid())
    or (user_id is null and anonymous_id is not null)
  )
);

drop policy if exists "Clients can update fact read events" on public.fact_read_events;
create policy "Clients can update fact read events"
on public.fact_read_events for update
to anon, authenticated
using (
  (auth.uid() is not null and user_id = auth.uid())
  or (user_id is null and anonymous_id is not null)
)
with check (
  (auth.uid() is not null and user_id = auth.uid())
  or (user_id is null and anonymous_id is not null)
);

drop policy if exists "Admins can read fact read events" on public.fact_read_events;
create policy "Admins can read fact read events"
on public.fact_read_events for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can read fact engagement stats" on public.fact_engagement_stats;
create policy "Admins can read fact engagement stats"
on public.fact_engagement_stats for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can read feed sessions" on public.feed_sessions;
create policy "Admins can read feed sessions"
on public.feed_sessions for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can read feed session items" on public.feed_session_items;
create policy "Admins can read feed session items"
on public.feed_session_items for select
to authenticated
using (public.is_admin());

drop function if exists public.get_personalized_feed(uuid, integer, uuid, boolean);
drop function if exists public.get_personalized_feed(uuid, integer, uuid, boolean, text);

create or replace function public.get_personalized_feed(
  p_user_id uuid default null,
  p_limit integer default 20,
  p_session_id uuid default null,
  p_debug boolean default false,
  p_theme_slug text default null
)
returns table (
  id uuid,
  slug text,
  title text,
  hook text,
  content text,
  source text,
  source_url text,
  difficulty_level text,
  long_content text,
  seo_title text,
  seo_description text,
  event_day integer,
  event_month integer,
  event_year integer,
  published_at timestamptz,
  updated_at timestamptz,
  tone text,
  accent_color text,
  category_id uuid,
  category_name text,
  category_slug text,
  category_tone text,
  category_accent_color text,
  seen_by_user boolean,
  recommendation_score numeric,
  score_debug jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_auth_user_id uuid := auth.uid();
  v_is_admin boolean := coalesce(public.is_admin(), false);
  v_user_id uuid := null;
  v_limit integer := greatest(1, least(coalesce(p_limit, 20), 50));
  v_pool_limit integer := greatest(200, least(500, v_limit * 18));
  v_debug boolean := coalesce(p_debug, false) and v_is_admin;
  v_learning_goal text := 'strengthen';
begin
  if v_is_admin and p_user_id is not null then
    v_user_id := p_user_id;
  elsif v_auth_user_id is not null then
    v_user_id := v_auth_user_id;
  else
    v_user_id := null;
  end if;

  select coalesce(profiles.learning_goal, 'strengthen')
  into v_learning_goal
  from public.profiles
  where profiles.id = v_user_id;

  v_learning_goal := coalesce(v_learning_goal, 'strengthen');

  if v_learning_goal not in ('basics', 'strengthen', 'advanced') then
    v_learning_goal := 'strengthen';
  end if;

  if p_session_id is not null then
    insert into public.feed_sessions (id, user_id, last_seen_at)
    values (p_session_id, v_user_id, now())
    on conflict on constraint feed_sessions_pkey do update set
      user_id = coalesce(excluded.user_id, public.feed_sessions.user_id),
      last_seen_at = now();
  end if;

  return query
  with theme_affinity as (
    select
      source.category_id,
      count(*)::numeric as affinity_count
    from (
      select facts.category_id
      from public.likes
      join public.facts on facts.id = likes.fact_id
      where likes.user_id = v_user_id
      union all
      select facts.category_id
      from public.saves
      join public.facts on facts.id = saves.fact_id
      where saves.user_id = v_user_id
      union all
      select facts.category_id
      from public.user_fact_views
      join public.facts on facts.id = user_fact_views.fact_id
      where user_fact_views.user_id = v_user_id
        and user_fact_views.first_viewed_at >= now() - interval '45 days'
    ) source
    group by source.category_id
  ),
  candidate_pool as (
    (
    select facts.id
    from public.facts
    join public.categories on categories.id = facts.category_id
    where facts.status = 'published'
      and (p_theme_slug is null or categories.slug = p_theme_slug)
      and not exists (
        select 1
        from public.user_fact_views
        where user_fact_views.user_id = v_user_id
          and user_fact_views.fact_id = facts.id
    )
    order by facts.published_at desc nulls last, facts.updated_at desc
    limit v_pool_limit / 2
    )

    union

    (
    select facts.id
    from public.facts
    join public.categories on categories.id = facts.category_id
    where facts.status = 'published'
      and (p_theme_slug is null or categories.slug = p_theme_slug)
      and facts.published_at >= now() - interval '90 days'
    order by facts.published_at desc nulls last, facts.updated_at desc
    limit v_pool_limit / 4
    )

    union

    (
    select facts.id
    from public.facts
    join public.categories on categories.id = facts.category_id
    join theme_affinity on theme_affinity.category_id = facts.category_id
    where facts.status = 'published'
      and (p_theme_slug is null or categories.slug = p_theme_slug)
    order by theme_affinity.affinity_count desc, facts.published_at desc nulls last
    limit v_pool_limit / 4
    )

    union

    (
    select facts.id
    from public.facts
    join public.categories on categories.id = facts.category_id
    where facts.status = 'published'
      and (p_theme_slug is null or categories.slug = p_theme_slug)
      and facts.event_month = extract(month from current_date)::integer
      and facts.event_day between greatest(1, extract(day from current_date)::integer - 2)
        and least(31, extract(day from current_date)::integer + 2)
    order by abs(facts.event_day - extract(day from current_date)::integer), facts.published_at desc nulls last
    limit 60
    )

    union

    (
    select facts.id
    from public.facts
    join public.categories on categories.id = facts.category_id
    where facts.status = 'published'
      and (p_theme_slug is null or categories.slug = p_theme_slug)
    order by random()
    limit greatest(40, v_limit * 3)
    )
  ),
  hydrated as (
    select
      facts.*,
      categories.name as category_name,
      categories.slug as category_slug,
      categories.tone as category_tone,
      categories.accent_color as category_accent_color,
      user_fact_views.first_viewed_at,
      feed_session_items.served_at,
      coalesce(theme_affinity.affinity_count, 0) as affinity_count,
      coalesce(fact_engagement_stats.views_count, 0) as views_count,
      coalesce(fact_engagement_stats.unique_viewers_count, 0) as unique_viewers_count,
      coalesce(fact_engagement_stats.likes_count, 0) as likes_count,
      coalesce(fact_engagement_stats.saves_count, 0) as saves_count,
      coalesce(fact_engagement_stats.shares_count, 0) as shares_count
    from candidate_pool
    join public.facts on facts.id = candidate_pool.id
    join public.categories on categories.id = facts.category_id
    left join public.user_fact_views
      on user_fact_views.fact_id = facts.id
      and user_fact_views.user_id = v_user_id
    left join public.feed_session_items
      on feed_session_items.fact_id = facts.id
      and feed_session_items.session_id = p_session_id
    left join theme_affinity on theme_affinity.category_id = facts.category_id
    left join public.fact_engagement_stats on fact_engagement_stats.fact_id = facts.id
  ),
  scored as (
    select
      hydrated.*,
      100::numeric as base_score,
      case
        when hydrated.first_viewed_at is null then 45
        when hydrated.first_viewed_at >= now() - interval '1 day' then -90
        when hydrated.first_viewed_at >= now() - interval '7 days' then -55
        when hydrated.first_viewed_at >= now() - interval '30 days' then -25
        else -8
      end::numeric as seen_penalty,
      case
        when hydrated.served_at is null then 0
        when hydrated.served_at >= now() - interval '30 minutes' then -80
        when hydrated.served_at >= now() - interval '6 hours' then -40
        else -15
      end::numeric as session_penalty,
      least(35, hydrated.affinity_count * 6)::numeric as theme_affinity_bonus,
      case
        when v_learning_goal = 'basics' and hydrated.difficulty_level = 'basic' then 25
        when v_learning_goal = 'basics' and hydrated.difficulty_level = 'intermediate' then 8
        when v_learning_goal = 'basics' then -15
        when v_learning_goal = 'advanced' and hydrated.difficulty_level = 'advanced' then 25
        when v_learning_goal = 'advanced' and hydrated.difficulty_level = 'intermediate' then 10
        when v_learning_goal = 'advanced' then -12
        when hydrated.difficulty_level = 'intermediate' then 25
        else 8
      end::numeric as level_match_bonus,
      case
        when hydrated.published_at >= now() - interval '7 days' then 14
        when hydrated.published_at >= now() - interval '30 days' then 8
        when hydrated.published_at >= now() - interval '90 days' then 3
        else 0
      end::numeric as freshness_bonus,
      case
        when hydrated.event_month = extract(month from current_date)::integer
          and hydrated.event_day = extract(day from current_date)::integer then 30
        when hydrated.event_month = extract(month from current_date)::integer
          and abs(hydrated.event_day - extract(day from current_date)::integer) <= 2 then 12
        else 0
      end::numeric as date_relevance_bonus,
      least(
        18,
        ln(1 + hydrated.views_count + hydrated.unique_viewers_count * 2 + hydrated.likes_count * 4 + hydrated.saves_count * 5 + hydrated.shares_count * 3) * 3
      )::numeric as engagement_bonus,
      (random() * 8)::numeric as random_bonus
    from hydrated
  ),
  ranked as (
    select
      scored.*,
      (
        scored.base_score +
        scored.seen_penalty +
        scored.session_penalty +
        scored.theme_affinity_bonus +
        scored.level_match_bonus +
        scored.freshness_bonus +
        scored.date_relevance_bonus +
        scored.engagement_bonus +
        scored.random_bonus
      )::numeric as final_score
    from scored
    order by final_score desc
    limit v_limit
  ),
  remembered as (
    insert into public.feed_session_items (session_id, fact_id, served_at)
    select p_session_id, ranked.id, now()
    from ranked
    where p_session_id is not null
    on conflict (session_id, fact_id) do update set served_at = excluded.served_at
    returning fact_id
  )
  select
    ranked.id,
    ranked.slug,
    ranked.title,
    ranked.hook,
    ranked.content,
    ranked.source,
    ranked.source_url,
    ranked.difficulty_level,
    ranked.long_content,
    ranked.seo_title,
    ranked.seo_description,
    ranked.event_day,
    ranked.event_month,
    ranked.event_year,
    ranked.published_at,
    ranked.updated_at,
    ranked.tone,
    ranked.accent_color,
    ranked.category_id,
    ranked.category_name,
    ranked.category_slug,
    ranked.category_tone,
    ranked.category_accent_color,
    ranked.first_viewed_at is not null as seen_by_user,
    round(ranked.final_score, 2) as recommendation_score,
    case
      when v_debug then jsonb_build_object(
        'base_score', ranked.base_score,
        'seen_penalty', ranked.seen_penalty,
        'session_penalty', ranked.session_penalty,
        'theme_affinity_bonus', ranked.theme_affinity_bonus,
        'level_match_bonus', ranked.level_match_bonus,
        'freshness_bonus', ranked.freshness_bonus,
        'date_relevance_bonus', ranked.date_relevance_bonus,
        'engagement_bonus', ranked.engagement_bonus,
        'random_bonus', round(ranked.random_bonus, 2),
        'final_score', round(ranked.final_score, 2)
      )
      else null
    end as score_debug
  from ranked;
end;
$$;

comment on function public.get_personalized_feed(uuid, integer, uuid, boolean, text) is
  'Personalized feed V2. Builds a bounded candidate pool from indexed subsets, scores only that pool, and records served facts in feed_session_items to reduce scroll duplicates.';

grant execute on function public.get_personalized_feed(uuid, integer, uuid, boolean, text) to anon;
grant execute on function public.get_personalized_feed(uuid, integer, uuid, boolean, text) to authenticated;
